// Code generated by command: go run blake2sp_gen.go -pkg rarengine -out ../blake2sp_amd64.s -stubs ../blake2sp_amd64.go. DO NOT EDIT.

//go:build amd64

#include "textflag.h"

DATA blake2sIV8<>+0(SB)/4, $0x6a09e667
DATA blake2sIV8<>+4(SB)/4, $0xbb67ae85
DATA blake2sIV8<>+8(SB)/4, $0x3c6ef372
DATA blake2sIV8<>+12(SB)/4, $0xa54ff53a
DATA blake2sIV8<>+16(SB)/4, $0x510e527f
DATA blake2sIV8<>+20(SB)/4, $0x9b05688c
DATA blake2sIV8<>+24(SB)/4, $0x1f83d9ab
DATA blake2sIV8<>+28(SB)/4, $0x5be0cd19
GLOBL blake2sIV8<>(SB), RODATA|NOPTR, $32

DATA blake2sRot16<>+0(SB)/1, $0x02
DATA blake2sRot16<>+1(SB)/1, $0x03
DATA blake2sRot16<>+2(SB)/1, $0x00
DATA blake2sRot16<>+3(SB)/1, $0x01
DATA blake2sRot16<>+4(SB)/1, $0x06
DATA blake2sRot16<>+5(SB)/1, $0x07
DATA blake2sRot16<>+6(SB)/1, $0x04
DATA blake2sRot16<>+7(SB)/1, $0x05
DATA blake2sRot16<>+8(SB)/1, $0x0a
DATA blake2sRot16<>+9(SB)/1, $0x0b
DATA blake2sRot16<>+10(SB)/1, $0x08
DATA blake2sRot16<>+11(SB)/1, $0x09
DATA blake2sRot16<>+12(SB)/1, $0x0e
DATA blake2sRot16<>+13(SB)/1, $0x0f
DATA blake2sRot16<>+14(SB)/1, $0x0c
DATA blake2sRot16<>+15(SB)/1, $0x0d
DATA blake2sRot16<>+16(SB)/1, $0x02
DATA blake2sRot16<>+17(SB)/1, $0x03
DATA blake2sRot16<>+18(SB)/1, $0x00
DATA blake2sRot16<>+19(SB)/1, $0x01
DATA blake2sRot16<>+20(SB)/1, $0x06
DATA blake2sRot16<>+21(SB)/1, $0x07
DATA blake2sRot16<>+22(SB)/1, $0x04
DATA blake2sRot16<>+23(SB)/1, $0x05
DATA blake2sRot16<>+24(SB)/1, $0x0a
DATA blake2sRot16<>+25(SB)/1, $0x0b
DATA blake2sRot16<>+26(SB)/1, $0x08
DATA blake2sRot16<>+27(SB)/1, $0x09
DATA blake2sRot16<>+28(SB)/1, $0x0e
DATA blake2sRot16<>+29(SB)/1, $0x0f
DATA blake2sRot16<>+30(SB)/1, $0x0c
DATA blake2sRot16<>+31(SB)/1, $0x0d
GLOBL blake2sRot16<>(SB), RODATA|NOPTR, $32

DATA blake2sRot8<>+0(SB)/1, $0x01
DATA blake2sRot8<>+1(SB)/1, $0x02
DATA blake2sRot8<>+2(SB)/1, $0x03
DATA blake2sRot8<>+3(SB)/1, $0x00
DATA blake2sRot8<>+4(SB)/1, $0x05
DATA blake2sRot8<>+5(SB)/1, $0x06
DATA blake2sRot8<>+6(SB)/1, $0x07
DATA blake2sRot8<>+7(SB)/1, $0x04
DATA blake2sRot8<>+8(SB)/1, $0x09
DATA blake2sRot8<>+9(SB)/1, $0x0a
DATA blake2sRot8<>+10(SB)/1, $0x0b
DATA blake2sRot8<>+11(SB)/1, $0x08
DATA blake2sRot8<>+12(SB)/1, $0x0d
DATA blake2sRot8<>+13(SB)/1, $0x0e
DATA blake2sRot8<>+14(SB)/1, $0x0f
DATA blake2sRot8<>+15(SB)/1, $0x0c
DATA blake2sRot8<>+16(SB)/1, $0x01
DATA blake2sRot8<>+17(SB)/1, $0x02
DATA blake2sRot8<>+18(SB)/1, $0x03
DATA blake2sRot8<>+19(SB)/1, $0x00
DATA blake2sRot8<>+20(SB)/1, $0x05
DATA blake2sRot8<>+21(SB)/1, $0x06
DATA blake2sRot8<>+22(SB)/1, $0x07
DATA blake2sRot8<>+23(SB)/1, $0x04
DATA blake2sRot8<>+24(SB)/1, $0x09
DATA blake2sRot8<>+25(SB)/1, $0x0a
DATA blake2sRot8<>+26(SB)/1, $0x0b
DATA blake2sRot8<>+27(SB)/1, $0x08
DATA blake2sRot8<>+28(SB)/1, $0x0d
DATA blake2sRot8<>+29(SB)/1, $0x0e
DATA blake2sRot8<>+30(SB)/1, $0x0f
DATA blake2sRot8<>+31(SB)/1, $0x0c
GLOBL blake2sRot8<>(SB), RODATA|NOPTR, $32

// func blake2sp8AVX2(h *[8][8]uint32, p *byte, strides int, t uint64)
// Requires: AVX, AVX2
TEXT ·blake2sp8AVX2(SB), NOSPLIT, $576-32
	MOVQ  h+0(FP), AX
	MOVQ  p+8(FP), CX
	MOVQ  strides+16(FP), DX
	MOVQ  t+24(FP), BX
	TESTQ DX, DX
	JZ    done

stride:
	VMOVDQU      (CX), Y0
	VMOVDQU      64(CX), Y1
	VMOVDQU      128(CX), Y2
	VMOVDQU      192(CX), Y3
	VMOVDQU      256(CX), Y4
	VMOVDQU      320(CX), Y5
	VMOVDQU      384(CX), Y6
	VMOVDQU      448(CX), Y7
	VPUNPCKLDQ   Y1, Y0, Y8
	VPUNPCKHDQ   Y1, Y0, Y9
	VPUNPCKLDQ   Y3, Y2, Y10
	VPUNPCKHDQ   Y3, Y2, Y11
	VPUNPCKLDQ   Y5, Y4, Y12
	VPUNPCKHDQ   Y5, Y4, Y13
	VPUNPCKLDQ   Y7, Y6, Y14
	VPUNPCKHDQ   Y7, Y6, Y15
	VPUNPCKLQDQ  Y10, Y8, Y0
	VPUNPCKHQDQ  Y10, Y8, Y1
	VPUNPCKLQDQ  Y11, Y9, Y2
	VPUNPCKHQDQ  Y11, Y9, Y3
	VPUNPCKLQDQ  Y14, Y12, Y4
	VPUNPCKHQDQ  Y14, Y12, Y5
	VPUNPCKLQDQ  Y15, Y13, Y6
	VPUNPCKHQDQ  Y15, Y13, Y7
	VPERM2I128   $0x20, Y4, Y0, Y8
	VPERM2I128   $0x31, Y4, Y0, Y9
	VMOVDQU      Y8, (SP)
	VMOVDQU      Y9, 128(SP)
	VPERM2I128   $0x20, Y5, Y1, Y8
	VPERM2I128   $0x31, Y5, Y1, Y9
	VMOVDQU      Y8, 32(SP)
	VMOVDQU      Y9, 160(SP)
	VPERM2I128   $0x20, Y6, Y2, Y8
	VPERM2I128   $0x31, Y6, Y2, Y9
	VMOVDQU      Y8, 64(SP)
	VMOVDQU      Y9, 192(SP)
	VPERM2I128   $0x20, Y7, Y3, Y8
	VPERM2I128   $0x31, Y7, Y3, Y9
	VMOVDQU      Y8, 96(SP)
	VMOVDQU      Y9, 224(SP)
	VMOVDQU      32(CX), Y0
	VMOVDQU      96(CX), Y1
	VMOVDQU      160(CX), Y2
	VMOVDQU      224(CX), Y3
	VMOVDQU      288(CX), Y4
	VMOVDQU      352(CX), Y5
	VMOVDQU      416(CX), Y6
	VMOVDQU      480(CX), Y7
	VPUNPCKLDQ   Y1, Y0, Y8
	VPUNPCKHDQ   Y1, Y0, Y9
	VPUNPCKLDQ   Y3, Y2, Y10
	VPUNPCKHDQ   Y3, Y2, Y11
	VPUNPCKLDQ   Y5, Y4, Y12
	VPUNPCKHDQ   Y5, Y4, Y13
	VPUNPCKLDQ   Y7, Y6, Y14
	VPUNPCKHDQ   Y7, Y6, Y15
	VPUNPCKLQDQ  Y10, Y8, Y0
	VPUNPCKHQDQ  Y10, Y8, Y1
	VPUNPCKLQDQ  Y11, Y9, Y2
	VPUNPCKHQDQ  Y11, Y9, Y3
	VPUNPCKLQDQ  Y14, Y12, Y4
	VPUNPCKHQDQ  Y14, Y12, Y5
	VPUNPCKLQDQ  Y15, Y13, Y6
	VPUNPCKHQDQ  Y15, Y13, Y7
	VPERM2I128   $0x20, Y4, Y0, Y8
	VPERM2I128   $0x31, Y4, Y0, Y9
	VMOVDQU      Y8, 256(SP)
	VMOVDQU      Y9, 384(SP)
	VPERM2I128   $0x20, Y5, Y1, Y8
	VPERM2I128   $0x31, Y5, Y1, Y9
	VMOVDQU      Y8, 288(SP)
	VMOVDQU      Y9, 416(SP)
	VPERM2I128   $0x20, Y6, Y2, Y8
	VPERM2I128   $0x31, Y6, Y2, Y9
	VMOVDQU      Y8, 320(SP)
	VMOVDQU      Y9, 448(SP)
	VPERM2I128   $0x20, Y7, Y3, Y8
	VPERM2I128   $0x31, Y7, Y3, Y9
	VMOVDQU      Y8, 352(SP)
	VMOVDQU      Y9, 480(SP)
	VMOVDQU      (AX), Y0
	VMOVDQU      32(AX), Y1
	VMOVDQU      64(AX), Y2
	VMOVDQU      96(AX), Y3
	VMOVDQU      128(AX), Y4
	VMOVDQU      160(AX), Y5
	VMOVDQU      192(AX), Y6
	VMOVDQU      224(AX), Y7
	LEAQ         blake2sIV8<>+0(SB), SI
	VPBROADCASTD (SI), Y8
	VPBROADCASTD 4(SI), Y9
	VPBROADCASTD 8(SI), Y10
	VPBROADCASTD 12(SI), Y11
	ADDQ         $0x40, BX
	MOVQ         BX, DI
	VMOVD        DI, X15
	VPBROADCASTD X15, Y12
	VPBROADCASTD 16(SI), Y15
	VPXOR        Y15, Y12, Y12
	SHRQ         $0x20, DI
	VMOVD        DI, X15
	VPBROADCASTD X15, Y13
	VPBROADCASTD 20(SI), Y15
	VPXOR        Y15, Y13, Y13
	VPBROADCASTD 24(SI), Y15
	VMOVDQU      Y15, 512(SP)
	VPBROADCASTD 28(SI), Y15
	VMOVDQU      Y15, 544(SP)
	VPADDD       Y4, Y0, Y0
	VPADDD       (SP), Y0, Y0
	VPXOR        Y0, Y12, Y12
	VPSHUFB      blake2sRot16<>+0(SB), Y12, Y12
	VPADDD       Y12, Y8, Y8
	VPXOR        Y8, Y4, Y4
	VPSRLD       $0x0c, Y4, Y15
	VPSLLD       $0x14, Y4, Y4
	VPOR         Y15, Y4, Y4
	VPADDD       Y4, Y0, Y0
	VPADDD       32(SP), Y0, Y0
	VPXOR        Y0, Y12, Y12
	VPSHUFB      blake2sRot8<>+0(SB), Y12, Y12
	VPADDD       Y12, Y8, Y8
	VPXOR        Y8, Y4, Y4
	VPSRLD       $0x07, Y4, Y15
	VPSLLD       $0x19, Y4, Y4
	VPOR         Y15, Y4, Y4
	VPADDD       Y5, Y1, Y1
	VPADDD       64(SP), Y1, Y1
	VPXOR        Y1, Y13, Y13
	VPSHUFB      blake2sRot16<>+0(SB), Y13, Y13
	VPADDD       Y13, Y9, Y9
	VPXOR        Y9, Y5, Y5
	VPSRLD       $0x0c, Y5, Y15
	VPSLLD       $0x14, Y5, Y5
	VPOR         Y15, Y5, Y5
	VPADDD       Y5, Y1, Y1
	VPADDD       96(SP), Y1, Y1
	VPXOR        Y1, Y13, Y13
	VPSHUFB      blake2sRot8<>+0(SB), Y13, Y13
	VPADDD       Y13, Y9, Y9
	VPXOR        Y9, Y5, Y5
	VPSRLD       $0x07, Y5, Y15
	VPSLLD       $0x19, Y5, Y5
	VPOR         Y15, Y5, Y5
	VMOVDQU      512(SP), Y14
	VPADDD       Y6, Y2, Y2
	VPADDD       128(SP), Y2, Y2
	VPXOR        Y2, Y14, Y14
	VPSHUFB      blake2sRot16<>+0(SB), Y14, Y14
	VPADDD       Y14, Y10, Y10
	VPXOR        Y10, Y6, Y6
	VPSRLD       $0x0c, Y6, Y15
	VPSLLD       $0x14, Y6, Y6
	VPOR         Y15, Y6, Y6
	VPADDD       Y6, Y2, Y2
	VPADDD       160(SP), Y2, Y2
	VPXOR        Y2, Y14, Y14
	VPSHUFB      blake2sRot8<>+0(SB), Y14, Y14
	VPADDD       Y14, Y10, Y10
	VPXOR        Y10, Y6, Y6
	VPSRLD       $0x07, Y6, Y15
	VPSLLD       $0x19, Y6, Y6
	VPOR         Y15, Y6, Y6
	VMOVDQU      Y14, 512(SP)
	VMOVDQU      544(SP), Y14
	VPADDD       Y7, Y3, Y3
	VPADDD       192(SP), Y3, Y3
	VPXOR        Y3, Y14, Y14
	VPSHUFB      blake2sRot16<>+0(SB), Y14, Y14
	VPADDD       Y14, Y11, Y11
	VPXOR        Y11, Y7, Y7
	VPSRLD       $0x0c, Y7, Y15
	VPSLLD       $0x14, Y7, Y7
	VPOR         Y15, Y7, Y7
	VPADDD       Y7, Y3, Y3
	VPADDD       224(SP), Y3, Y3
	VPXOR        Y3, Y14, Y14
	VPSHUFB      blake2sRot8<>+0(SB), Y14, Y14
	VPADDD       Y14, Y11, Y11
	VPXOR        Y11, Y7, Y7
	VPSRLD       $0x07, Y7, Y15
	VPSLLD       $0x19, Y7, Y7
	VPOR         Y15, Y7, Y7
	VMOVDQU      Y14, 544(SP)
	VMOVDQU      544(SP), Y14
	VPADDD       Y5, Y0, Y0
	VPADDD       256(SP), Y0, Y0
	VPXOR        Y0, Y14, Y14
	VPSHUFB      blake2sRot16<>+0(SB), Y14, Y14
	VPADDD       Y14, Y10, Y10
	VPXOR        Y10, Y5, Y5
	VPSRLD       $0x0c, Y5, Y15
	VPSLLD       $0x14, Y5, Y5
	VPOR         Y15, Y5, Y5
	VPADDD       Y5, Y0, Y0
	VPADDD       288(SP), Y0, Y0
	VPXOR        Y0, Y14, Y14
	VPSHUFB      blake2sRot8<>+0(SB), Y14, Y14
	VPADDD       Y14, Y10, Y10
	VPXOR        Y10, Y5, Y5
	VPSRLD       $0x07, Y5, Y15
	VPSLLD       $0x19, Y5, Y5
	VPOR         Y15, Y5, Y5
	VMOVDQU      Y14, 544(SP)
	VPADDD       Y6, Y1, Y1
	VPADDD       320(SP), Y1, Y1
	VPXOR        Y1, Y12, Y12
	VPSHUFB      blake2sRot16<>+0(SB), Y12, Y12
	VPADDD       Y12, Y11, Y11
	VPXOR        Y11, Y6, Y6
	VPSRLD       $0x0c, Y6, Y15
	VPSLLD       $0x14, Y6, Y6
	VPOR         Y15, Y6, Y6
	VPADDD       Y6, Y1, Y1
	VPADDD       352(SP), Y1, Y1
	VPXOR        Y1, Y12, Y12
	VPSHUFB      blake2sRot8<>+0(SB), Y12, Y12
	VPADDD       Y12, Y11, Y11
	VPXOR        Y11, Y6, Y6
	VPSRLD       $0x07, Y6, Y15
	VPSLLD       $0x19, Y6, Y6
	VPOR         Y15, Y6, Y6
	VPADDD       Y7, Y2, Y2
	VPADDD       384(SP), Y2, Y2
	VPXOR        Y2, Y13, Y13
	VPSHUFB      blake2sRot16<>+0(SB), Y13, Y13
	VPADDD       Y13, Y8, Y8
	VPXOR        Y8, Y7, Y7
	VPSRLD       $0x0c, Y7, Y15
	VPSLLD       $0x14, Y7, Y7
	VPOR         Y15, Y7, Y7
	VPADDD       Y7, Y2, Y2
	VPADDD       416(SP), Y2, Y2
	VPXOR        Y2, Y13, Y13
	VPSHUFB      blake2sRot8<>+0(SB), Y13, Y13
	VPADDD       Y13, Y8, Y8
	VPXOR        Y8, Y7, Y7
	VPSRLD       $0x07, Y7, Y15
	VPSLLD       $0x19, Y7, Y7
	VPOR         Y15, Y7, Y7
	VMOVDQU      512(SP), Y14
	VPADDD       Y4, Y3, Y3
	VPADDD       448(SP), Y3, Y3
	VPXOR        Y3, Y14, Y14
	VPSHUFB      blake2sRot16<>+0(SB), Y14, Y14
	VPADDD       Y14, Y9, Y9
	VPXOR        Y9, Y4, Y4
	VPSRLD       $0x0c, Y4, Y15
	VPSLLD       $0x14, Y4, Y4
	VPOR         Y15, Y4, Y4
	VPADDD       Y4, Y3, Y3
	VPADDD       480(SP), Y3, Y3
	VPXOR        Y3, Y14, Y14
	VPSHUFB      blake2sRot8<>+0(SB), Y14, Y14
	VPADDD       Y14, Y9, Y9
	VPXOR        Y9, Y4, Y4
	VPSRLD       $0x07, Y4, Y15
	VPSLLD       $0x19, Y4, Y4
	VPOR         Y15, Y4, Y4
	VMOVDQU      Y14, 512(SP)
	VPADDD       Y4, Y0, Y0
	VPADDD       448(SP), Y0, Y0
	VPXOR        Y0, Y12, Y12
	VPSHUFB      blake2sRot16<>+0(SB), Y12, Y12
	VPADDD       Y12, Y8, Y8
	VPXOR        Y8, Y4, Y4
	VPSRLD       $0x0c, Y4, Y15
	VPSLLD       $0x14, Y4, Y4
	VPOR         Y15, Y4, Y4
	VPADDD       Y4, Y0, Y0
	VPADDD       320(SP), Y0, Y0
	VPXOR        Y0, Y12, Y12
	VPSHUFB      blake2sRot8<>+0(SB), Y12, Y12
	VPADDD       Y12, Y8, Y8
	VPXOR        Y8, Y4, Y4
	VPSRLD       $0x07, Y4, Y15
	VPSLLD       $0x19, Y4, Y4
	VPOR         Y15, Y4, Y4
	VPADDD       Y5, Y1, Y1
	VPADDD       128(SP), Y1, Y1
	VPXOR        Y1, Y13, Y13
	VPSHUFB      blake2sRot16<>+0(SB), Y13, Y13
	VPADDD       Y13, Y9, Y9
	VPXOR        Y9, Y5, Y5
	VPSRLD       $0x0c, Y5, Y15
	VPSLLD       $0x14, Y5, Y5
	VPOR         Y15, Y5, Y5
	VPADDD       Y5, Y1, Y1
	VPADDD       256(SP), Y1, Y1
	VPXOR        Y1, Y13, Y13
	VPSHUFB      blake2sRot8<>+0(SB), Y13, Y13
	VPADDD       Y13, Y9, Y9
	VPXOR        Y9, Y5, Y5
	VPSRLD       $0x07, Y5, Y15
	VPSLLD       $0x19, Y5, Y5
	VPOR         Y15, Y5, Y5
	VMOVDQU      512(SP), Y14
	VPADDD       Y6, Y2, Y2
	VPADDD       288(SP), Y2, Y2
	VPXOR        Y2, Y14, Y14
	VPSHUFB      blake2sRot16<>+0(SB), Y14, Y14
	VPADDD       Y14, Y10, Y10
	VPXOR        Y10, Y6, Y6
	VPSRLD       $0x0c, Y6, Y15
	VPSLLD       $0x14, Y6, Y6
	VPOR         Y15, Y6, Y6
	VPADDD       Y6, Y2, Y2
	VPADDD       480(SP), Y2, Y2
	VPXOR        Y2, Y14, Y14
	VPSHUFB      blake2sRot8<>+0(SB), Y14, Y14
	VPADDD       Y14, Y10, Y10
	VPXOR        Y10, Y6, Y6
	VPSRLD       $0x07, Y6, Y15
	VPSLLD       $0x19, Y6, Y6
	VPOR         Y15, Y6, Y6
	VMOVDQU      Y14, 512(SP)
	VMOVDQU      544(SP), Y14
	VPADDD       Y7, Y3, Y3
	VPADDD       416(SP), Y3, Y3
	VPXOR        Y3, Y14, Y14
	VPSHUFB      blake2sRot16<>+0(SB), Y14, Y14
	VPADDD       Y14, Y11, Y11
	VPXOR        Y11, Y7, Y7
	VPSRLD       $0x0c, Y7, Y15
	VPSLLD       $0x14, Y7, Y7
	VPOR         Y15, Y7, Y7
	VPADDD       Y7, Y3, Y3
	VPADDD       192(SP), Y3, Y3
	VPXOR        Y3, Y14, Y14
	VPSHUFB      blake2sRot8<>+0(SB), Y14, Y14
	VPADDD       Y14, Y11, Y11
	VPXOR        Y11, Y7, Y7
	VPSRLD       $0x07, Y7, Y15
	VPSLLD       $0x19, Y7, Y7
	VPOR         Y15, Y7, Y7
	VMOVDQU      Y14, 544(SP)
	VMOVDQU      544(SP), Y14
	VPADDD       Y5, Y0, Y0
	VPADDD       32(SP), Y0, Y0
	VPXOR        Y0, Y14, Y14
	VPSHUFB      blake2sRot16<>+0(SB), Y14, Y14
	VPADDD       Y14, Y10, Y10
	VPXOR        Y10, Y5, Y5
	VPSRLD       $0x0c, Y5, Y15
	VPSLLD       $0x14, Y5, Y5
	VPOR         Y15, Y5, Y5
	VPADDD       Y5, Y0, Y0
	VPADDD       384(SP), Y0, Y0
	VPXOR        Y0, Y14, Y14
	VPSHUFB      blake2sRot8<>+0(SB), Y14, Y14
	VPADDD       Y14, Y10, Y10
	VPXOR        Y10, Y5, Y5
	VPSRLD       $0x07, Y5, Y15
	VPSLLD       $0x19, Y5, Y5
	VPOR         Y15, Y5, Y5
	VMOVDQU      Y14, 544(SP)
	VPADDD       Y6, Y1, Y1
	VPADDD       (SP), Y1, Y1
	VPXOR        Y1, Y12, Y12
	VPSHUFB      blake2sRot16<>+0(SB), Y12, Y12
	VPADDD       Y12, Y11, Y11
	VPXOR        Y11, Y6, Y6
	VPSRLD       $0x0c, Y6, Y15
	VPSLLD       $0x14, Y6, Y6
	VPOR         Y15, Y6, Y6
	VPADDD       Y6, Y1, Y1
	VPADDD       64(SP), Y1, Y1
	VPXOR        Y1, Y12, Y12
	VPSHUFB      blake2sRot8<>+0(SB), Y12, Y12
	VPADDD       Y12, Y11, Y11
	VPXOR        Y11, Y6, Y6
	VPSRLD       $0x07, Y6, Y15
	VPSLLD       $0x19, Y6, Y6
	VPOR         Y15, Y6, Y6
	VPADDD       Y7, Y2, Y2
	VPADDD       352(SP), Y2, Y2
	VPXOR        Y2, Y13, Y13
	VPSHUFB      blake2sRot16<>+0(SB), Y13, Y13
	VPADDD       Y13, Y8, Y8
	VPXOR        Y8, Y7, Y7
	VPSRLD       $0x0c, Y7, Y15
	VPSLLD       $0x14, Y7, Y7
	VPOR         Y15, Y7, Y7
	VPADDD       Y7, Y2, Y2
	VPADDD       224(SP), Y2, Y2
	VPXOR        Y2, Y13, Y13
	VPSHUFB      blake2sRot8<>+0(SB), Y13, Y13
	VPADDD       Y13, Y8, Y8
	VPXOR        Y8, Y7, Y7
	VPSRLD       $0x07, Y7, Y15
	VPSLLD       $0x19, Y7, Y7
	VPOR         Y15, Y7, Y7
	VMOVDQU      512(SP), Y14
	VPADDD       Y4, Y3, Y3
	VPADDD       160(SP), Y3, Y3
	VPXOR        Y3, Y14, Y14
	VPSHUFB      blake2sRot16<>+0(SB), Y14, Y14
	VPADDD       Y14, Y9, Y9
	VPXOR        Y9, Y4, Y4
	VPSRLD       $0x0c, Y4, Y15
	VPSLLD       $0x14, Y4, Y4
	VPOR         Y15, Y4, Y4
	VPADDD       Y4, Y3, Y3
	VPADDD       96(SP), Y3, Y3
	VPXOR        Y3, Y14, Y14
	VPSHUFB      blake2sRot8<>+0(SB), Y14, Y14
	VPADDD       Y14, Y9, Y9
	VPXOR        Y9, Y4, Y4
	VPSRLD       $0x07, Y4, Y15
	VPSLLD       $0x19, Y4, Y4
	VPOR         Y15, Y4, Y4
	VMOVDQU      Y14, 512(SP)
	VPADDD       Y4, Y0, Y0
	VPADDD       352(SP), Y0, Y0
	VPXOR        Y0, Y12, Y12
	VPSHUFB      blake2sRot16<>+0(SB), Y12, Y12
	VPADDD       Y12, Y8, Y8
	VPXOR        Y8, Y4, Y4
	VPSRLD       $0x0c, Y4, Y15
	VPSLLD       $0x14, Y4, Y4
	VPOR         Y15, Y4, Y4
	VPADDD       Y4, Y0, Y0
	VPADDD       256(SP), Y0, Y0
	VPXOR        Y0, Y12, Y12
	VPSHUFB      blake2sRot8<>+0(SB), Y12, Y12
	VPADDD       Y12, Y8, Y8
	VPXOR        Y8, Y4, Y4
	VPSRLD       $0x07, Y4, Y15
	VPSLLD       $0x19, Y4, Y4
	VPOR         Y15, Y4, Y4
	VPADDD       Y5, Y1, Y1
	VPADDD       384(SP), Y1, Y1
	VPXOR        Y1, Y13, Y13
	VPSHUFB      blake2sRot16<>+0(SB), Y13, Y13
	VPADDD       Y13, Y9, Y9
	VPXOR        Y9, Y5, Y5
	VPSRLD       $0x0c, Y5, Y15
	VPSLLD       $0x14, Y5, Y5
	VPOR         Y15, Y5, Y5
	VPADDD       Y5, Y1, Y1
	VPADDD       (SP), Y1, Y1
	VPXOR        Y1, Y13, Y13
	VPSHUFB      blake2sRot8<>+0(SB), Y13, Y13
	VPADDD       Y13, Y9, Y9
	VPXOR        Y9, Y5, Y5
	VPSRLD       $0x07, Y5, Y15
	VPSLLD       $0x19, Y5, Y5
	VPOR         Y15, Y5, Y5
	VMOVDQU      512(SP), Y14
	VPADDD       Y6, Y2, Y2
	VPADDD       160(SP), Y2, Y2
	VPXOR        Y2, Y14, Y14
	VPSHUFB      blake2sRot16<>+0(SB), Y14, Y14
	VPADDD       Y14, Y10, Y10
	VPXOR        Y10, Y6, Y6
	VPSRLD       $0x0c, Y6, Y15
	VPSLLD       $0x14, Y6, Y6
	VPOR         Y15, Y6, Y6
	VPADDD       Y6, Y2, Y2
	VPADDD       64(SP), Y2, Y2
	VPXOR        Y2, Y14, Y14
	VPSHUFB      blake2sRot8<>+0(SB), Y14, Y14
	VPADDD       Y14, Y10, Y10
	VPXOR        Y10, Y6, Y6
	VPSRLD       $0x07, Y6, Y15
	VPSLLD       $0x19, Y6, Y6
	VPOR         Y15, Y6, Y6
	VMOVDQU      Y14, 512(SP)
	VMOVDQU      544(SP), Y14
	VPADDD       Y7, Y3, Y3
	VPADDD       480(SP), Y3, Y3
	VPXOR        Y3, Y14, Y14
	VPSHUFB      blake2sRot16<>+0(SB), Y14, Y14
	VPADDD       Y14, Y11, Y11
	VPXOR        Y11, Y7, Y7
	VPSRLD       $0x0c, Y7, Y15
	VPSLLD       $0x14, Y7, Y7
	VPOR         Y15, Y7, Y7
	VPADDD       Y7, Y3, Y3
	VPADDD       416(SP), Y3, Y3
	VPXOR        Y3, Y14, Y14
	VPSHUFB      blake2sRot8<>+0(SB), Y14, Y14
	VPADDD       Y14, Y11, Y11
	VPXOR        Y11, Y7, Y7
	VPSRLD       $0x07, Y7, Y15
	VPSLLD       $0x19, Y7, Y7
	VPOR         Y15, Y7, Y7
	VMOVDQU      Y14, 544(SP)
	VMOVDQU      544(SP), Y14
	VPADDD       Y5, Y0, Y0
	VPADDD       320(SP), Y0, Y0
	VPXOR        Y0, Y14, Y14
	VPSHUFB      blake2sRot16<>+0(SB), Y14, Y14
	VPADDD       Y14, Y10, Y10
	VPXOR        Y10, Y5, Y5
	VPSRLD       $0x0c, Y5, Y15
	VPSLLD       $0x14, Y5, Y5
	VPOR         Y15, Y5, Y5
	VPADDD       Y5, Y0, Y0
	VPADDD       448(SP), Y0, Y0
	VPXOR        Y0, Y14, Y14
	VPSHUFB      blake2sRot8<>+0(SB), Y14, Y14
	VPADDD       Y14, Y10, Y10
	VPXOR        Y10, Y5, Y5
	VPSRLD       $0x07, Y5, Y15
	VPSLLD       $0x19, Y5, Y5
	VPOR         Y15, Y5, Y5
	VMOVDQU      Y14, 544(SP)
	VPADDD       Y6, Y1, Y1
	VPADDD       96(SP), Y1, Y1
	VPXOR        Y1, Y12, Y12
	VPSHUFB      blake2sRot16<>+0(SB), Y12, Y12
	VPADDD       Y12, Y11, Y11
	VPXOR        Y11, Y6, Y6
	VPSRLD       $0x0c, Y6, Y15
	VPSLLD       $0x14, Y6, Y6
	VPOR         Y15, Y6, Y6
	VPADDD       Y6, Y1, Y1
	VPADDD       192(SP), Y1, Y1
	VPXOR        Y1, Y12, Y12
	VPSHUFB      blake2sRot8<>+0(SB), Y12, Y12
	VPADDD       Y12, Y11, Y11
	VPXOR        Y11, Y6, Y6
	VPSRLD       $0x07, Y6, Y15
	VPSLLD       $0x19, Y6, Y6
	VPOR         Y15, Y6, Y6
	VPADDD       Y7, Y2, Y2
	VPADDD       224(SP), Y2, Y2
	VPXOR        Y2, Y13, Y13
	VPSHUFB      blake2sRot16<>+0(SB), Y13, Y13
	VPADDD       Y13, Y8, Y8
	VPXOR        Y8, Y7, Y7
	VPSRLD       $0x0c, Y7, Y15
	VPSLLD       $0x14, Y7, Y7
	VPOR         Y15, Y7, Y7
	VPADDD       Y7, Y2, Y2
	VPADDD       32(SP), Y2, Y2
	VPXOR        Y2, Y13, Y13
	VPSHUFB      blake2sRot8<>+0(SB), Y13, Y13
	VPADDD       Y13, Y8, Y8
	VPXOR        Y8, Y7, Y7
	VPSRLD       $0x07, Y7, Y15
	VPSLLD       $0x19, Y7, Y7
	VPOR         Y15, Y7, Y7
	VMOVDQU      512(SP), Y14
	VPADDD       Y4, Y3, Y3
	VPADDD       288(SP), Y3, Y3
	VPXOR        Y3, Y14, Y14
	VPSHUFB      blake2sRot16<>+0(SB), Y14, Y14
	VPADDD       Y14, Y9, Y9
	VPXOR        Y9, Y4, Y4
	VPSRLD       $0x0c, Y4, Y15
	VPSLLD       $0x14, Y4, Y4
	VPOR         Y15, Y4, Y4
	VPADDD       Y4, Y3, Y3
	VPADDD       128(SP), Y3, Y3
	VPXOR        Y3, Y14, Y14
	VPSHUFB      blake2sRot8<>+0(SB), Y14, Y14
	VPADDD       Y14, Y9, Y9
	VPXOR        Y9, Y4, Y4
	VPSRLD       $0x07, Y4, Y15
	VPSLLD       $0x19, Y4, Y4
	VPOR         Y15, Y4, Y4
	VMOVDQU      Y14, 512(SP)
	VPADDD       Y4, Y0, Y0
	VPADDD       224(SP), Y0, Y0
	VPXOR        Y0, Y12, Y12
	VPSHUFB      blake2sRot16<>+0(SB), Y12, Y12
	VPADDD       Y12, Y8, Y8
	VPXOR        Y8, Y4, Y4
	VPSRLD       $0x0c, Y4, Y15
	VPSLLD       $0x14, Y4, Y4
	VPOR         Y15, Y4, Y4
	VPADDD       Y4, Y0, Y0
	VPADDD       288(SP), Y0, Y0
	VPXOR        Y0, Y12, Y12
	VPSHUFB      blake2sRot8<>+0(SB), Y12, Y12
	VPADDD       Y12, Y8, Y8
	VPXOR        Y8, Y4, Y4
	VPSRLD       $0x07, Y4, Y15
	VPSLLD       $0x19, Y4, Y4
	VPOR         Y15, Y4, Y4
	VPADDD       Y5, Y1, Y1
	VPADDD       96(SP), Y1, Y1
	VPXOR        Y1, Y13, Y13
	VPSHUFB      blake2sRot16<>+0(SB), Y13, Y13
	VPADDD       Y13, Y9, Y9
	VPXOR        Y9, Y5, Y5
	VPSRLD       $0x0c, Y5, Y15
	VPSLLD       $0x14, Y5, Y5
	VPOR         Y15, Y5, Y5
	VPADDD       Y5, Y1, Y1
	VPADDD       32(SP), Y1, Y1
	VPXOR        Y1, Y13, Y13
	VPSHUFB      blake2sRot8<>+0(SB), Y13, Y13
	VPADDD       Y13, Y9, Y9
	VPXOR        Y9, Y5, Y5
	VPSRLD       $0x07, Y5, Y15
	VPSLLD       $0x19, Y5, Y5
	VPOR         Y15, Y5, Y5
	VMOVDQU      512(SP), Y14
	VPADDD       Y6, Y2, Y2
	VPADDD       416(SP), Y2, Y2
	VPXOR        Y2, Y14, Y14
	VPSHUFB      blake2sRot16<>+0(SB), Y14, Y14
	VPADDD       Y14, Y10, Y10
	VPXOR        Y10, Y6, Y6
	VPSRLD       $0x0c, Y6, Y15
	VPSLLD       $0x14, Y6, Y6
	VPOR         Y15, Y6, Y6
	VPADDD       Y6, Y2, Y2
	VPADDD       384(SP), Y2, Y2
	VPXOR        Y2, Y14, Y14
	VPSHUFB      blake2sRot8<>+0(SB), Y14, Y14
	VPADDD       Y14, Y10, Y10
	VPXOR        Y10, Y6, Y6
	VPSRLD       $0x07, Y6, Y15
	VPSLLD       $0x19, Y6, Y6
	VPOR         Y15, Y6, Y6
	VMOVDQU      Y14, 512(SP)
	VMOVDQU      544(SP), Y14
	VPADDD       Y7, Y3, Y3
	VPADDD       352(SP), Y3, Y3
	VPXOR        Y3, Y14, Y14
	VPSHUFB      blake2sRot16<>+0(SB), Y14, Y14
	VPADDD       Y14, Y11, Y11
	VPXOR        Y11, Y7, Y7
	VPSRLD       $0x0c, Y7, Y15
	VPSLLD       $0x14, Y7, Y7
	VPOR         Y15, Y7, Y7
	VPADDD       Y7, Y3, Y3
	VPADDD       448(SP), Y3, Y3
	VPXOR        Y3, Y14, Y14
	VPSHUFB      blake2sRot8<>+0(SB), Y14, Y14
	VPADDD       Y14, Y11, Y11
	VPXOR        Y11, Y7, Y7
	VPSRLD       $0x07, Y7, Y15
	VPSLLD       $0x19, Y7, Y7
	VPOR         Y15, Y7, Y7
	VMOVDQU      Y14, 544(SP)
	VMOVDQU      544(SP), Y14
	VPADDD       Y5, Y0, Y0
	VPADDD       64(SP), Y0, Y0
	VPXOR        Y0, Y14, Y14
	VPSHUFB      blake2sRot16<>+0(SB), Y14, Y14
	VPADDD       Y14, Y10, Y10
	VPXOR        Y10, Y5, Y5
	VPSRLD       $0x0c, Y5, Y15
	VPSLLD       $0x14, Y5, Y5
	VPOR         Y15, Y5, Y5
	VPADDD       Y5, Y0, Y0
	VPADDD       192(SP), Y0, Y0
	VPXOR        Y0, Y14, Y14
	VPSHUFB      blake2sRot8<>+0(SB), Y14, Y14
	VPADDD       Y14, Y10, Y10
	VPXOR        Y10, Y5, Y5
	VPSRLD       $0x07, Y5, Y15
	VPSLLD       $0x19, Y5, Y5
	VPOR         Y15, Y5, Y5
	VMOVDQU      Y14, 544(SP)
	VPADDD       Y6, Y1, Y1
	VPADDD       160(SP), Y1, Y1
	VPXOR        Y1, Y12, Y12
	VPSHUFB      blake2sRot16<>+0(SB), Y12, Y12
	VPADDD       Y12, Y11, Y11
	VPXOR        Y11, Y6, Y6
	VPSRLD       $0x0c, Y6, Y15
	VPSLLD       $0x14, Y6, Y6
	VPOR         Y15, Y6, Y6
	VPADDD       Y6, Y1, Y1
	VPADDD       320(SP), Y1, Y1
	VPXOR        Y1, Y12, Y12
	VPSHUFB      blake2sRot8<>+0(SB), Y12, Y12
	VPADDD       Y12, Y11, Y11
	VPXOR        Y11, Y6, Y6
	VPSRLD       $0x07, Y6, Y15
	VPSLLD       $0x19, Y6, Y6
	VPOR         Y15, Y6, Y6
	VPADDD       Y7, Y2, Y2
	VPADDD       128(SP), Y2, Y2
	VPXOR        Y2, Y13, Y13
	VPSHUFB      blake2sRot16<>+0(SB), Y13, Y13
	VPADDD       Y13, Y8, Y8
	VPXOR        Y8, Y7, Y7
	VPSRLD       $0x0c, Y7, Y15
	VPSLLD       $0x14, Y7, Y7
	VPOR         Y15, Y7, Y7
	VPADDD       Y7, Y2, Y2
	VPADDD       (SP), Y2, Y2
	VPXOR        Y2, Y13, Y13
	VPSHUFB      blake2sRot8<>+0(SB), Y13, Y13
	VPADDD       Y13, Y8, Y8
	VPXOR        Y8, Y7, Y7
	VPSRLD       $0x07, Y7, Y15
	VPSLLD       $0x19, Y7, Y7
	VPOR         Y15, Y7, Y7
	VMOVDQU      512(SP), Y14
	VPADDD       Y4, Y3, Y3
	VPADDD       480(SP), Y3, Y3
	VPXOR        Y3, Y14, Y14
	VPSHUFB      blake2sRot16<>+0(SB), Y14, Y14
	VPADDD       Y14, Y9, Y9
	VPXOR        Y9, Y4, Y4
	VPSRLD       $0x0c, Y4, Y15
	VPSLLD       $0x14, Y4, Y4
	VPOR         Y15, Y4, Y4
	VPADDD       Y4, Y3, Y3
	VPADDD       256(SP), Y3, Y3
	VPXOR        Y3, Y14, Y14
	VPSHUFB      blake2sRot8<>+0(SB), Y14, Y14
	VPADDD       Y14, Y9, Y9
	VPXOR        Y9, Y4, Y4
	VPSRLD       $0x07, Y4, Y15
	VPSLLD       $0x19, Y4, Y4
	VPOR         Y15, Y4, Y4
	VMOVDQU      Y14, 512(SP)
	VPADDD       Y4, Y0, Y0
	VPADDD       288(SP), Y0, Y0
	VPXOR        Y0, Y12, Y12
	VPSHUFB      blake2sRot16<>+0(SB), Y12, Y12
	VPADDD       Y12, Y8, Y8
	VPXOR        Y8, Y4, Y4
	VPSRLD       $0x0c, Y4, Y15
	VPSLLD       $0x14, Y4, Y4
	VPOR         Y15, Y4, Y4
	VPADDD       Y4, Y0, Y0
	VPADDD       (SP), Y0, Y0
	VPXOR        Y0, Y12, Y12
	VPSHUFB      blake2sRot8<>+0(SB), Y12, Y12
	VPADDD       Y12, Y8, Y8
	VPXOR        Y8, Y4, Y4
	VPSRLD       $0x07, Y4, Y15
	VPSLLD       $0x19, Y4, Y4
	VPOR         Y15, Y4, Y4
	VPADDD       Y5, Y1, Y1
	VPADDD       160(SP), Y1, Y1
	VPXOR        Y1, Y13, Y13
	VPSHUFB      blake2sRot16<>+0(SB), Y13, Y13
	VPADDD       Y13, Y9, Y9
	VPXOR        Y9, Y5, Y5
	VPSRLD       $0x0c, Y5, Y15
	VPSLLD       $0x14, Y5, Y5
	VPOR         Y15, Y5, Y5
	VPADDD       Y5, Y1, Y1
	VPADDD       224(SP), Y1, Y1
	VPXOR        Y1, Y13, Y13
	VPSHUFB      blake2sRot8<>+0(SB), Y13, Y13
	VPADDD       Y13, Y9, Y9
	VPXOR        Y9, Y5, Y5
	VPSRLD       $0x07, Y5, Y15
	VPSLLD       $0x19, Y5, Y5
	VPOR         Y15, Y5, Y5
	VMOVDQU      512(SP), Y14
	VPADDD       Y6, Y2, Y2
	VPADDD       64(SP), Y2, Y2
	VPXOR        Y2, Y14, Y14
	VPSHUFB      blake2sRot16<>+0(SB), Y14, Y14
	VPADDD       Y14, Y10, Y10
	VPXOR        Y10, Y6, Y6
	VPSRLD       $0x0c, Y6, Y15
	VPSLLD       $0x14, Y6, Y6
	VPOR         Y15, Y6, Y6
	VPADDD       Y6, Y2, Y2
	VPADDD       128(SP), Y2, Y2
	VPXOR        Y2, Y14, Y14
	VPSHUFB      blake2sRot8<>+0(SB), Y14, Y14
	VPADDD       Y14, Y10, Y10
	VPXOR        Y10, Y6, Y6
	VPSRLD       $0x07, Y6, Y15
	VPSLLD       $0x19, Y6, Y6
	VPOR         Y15, Y6, Y6
	VMOVDQU      Y14, 512(SP)
	VMOVDQU      544(SP), Y14
	VPADDD       Y7, Y3, Y3
	VPADDD       320(SP), Y3, Y3
	VPXOR        Y3, Y14, Y14
	VPSHUFB      blake2sRot16<>+0(SB), Y14, Y14
	VPADDD       Y14, Y11, Y11
	VPXOR        Y11, Y7, Y7
	VPSRLD       $0x0c, Y7, Y15
	VPSLLD       $0x14, Y7, Y7
	VPOR         Y15, Y7, Y7
	VPADDD       Y7, Y3, Y3
	VPADDD       480(SP), Y3, Y3
	VPXOR        Y3, Y14, Y14
	VPSHUFB      blake2sRot8<>+0(SB), Y14, Y14
	VPADDD       Y14, Y11, Y11
	VPXOR        Y11, Y7, Y7
	VPSRLD       $0x07, Y7, Y15
	VPSLLD       $0x19, Y7, Y7
	VPOR         Y15, Y7, Y7
	VMOVDQU      Y14, 544(SP)
	VMOVDQU      544(SP), Y14
	VPADDD       Y5, Y0, Y0
	VPADDD       448(SP), Y0, Y0
	VPXOR        Y0, Y14, Y14
	VPSHUFB      blake2sRot16<>+0(SB), Y14, Y14
	VPADDD       Y14, Y10, Y10
	VPXOR        Y10, Y5, Y5
	VPSRLD       $0x0c, Y5, Y15
	VPSLLD       $0x14, Y5, Y5
	VPOR         Y15, Y5, Y5
	VPADDD       Y5, Y0, Y0
	VPADDD       32(SP), Y0, Y0
	VPXOR        Y0, Y14, Y14
	VPSHUFB      blake2sRot8<>+0(SB), Y14, Y14
	VPADDD       Y14, Y10, Y10
	VPXOR        Y10, Y5, Y5
	VPSRLD       $0x07, Y5, Y15
	VPSLLD       $0x19, Y5, Y5
	VPOR         Y15, Y5, Y5
	VMOVDQU      Y14, 544(SP)
	VPADDD       Y6, Y1, Y1
	VPADDD       352(SP), Y1, Y1
	VPXOR        Y1, Y12, Y12
	VPSHUFB      blake2sRot16<>+0(SB), Y12, Y12
	VPADDD       Y12, Y11, Y11
	VPXOR        Y11, Y6, Y6
	VPSRLD       $0x0c, Y6, Y15
	VPSLLD       $0x14, Y6, Y6
	VPOR         Y15, Y6, Y6
	VPADDD       Y6, Y1, Y1
	VPADDD       384(SP), Y1, Y1
	VPXOR        Y1, Y12, Y12
	VPSHUFB      blake2sRot8<>+0(SB), Y12, Y12
	VPADDD       Y12, Y11, Y11
	VPXOR        Y11, Y6, Y6
	VPSRLD       $0x07, Y6, Y15
	VPSLLD       $0x19, Y6, Y6
	VPOR         Y15, Y6, Y6
	VPADDD       Y7, Y2, Y2
	VPADDD       192(SP), Y2, Y2
	VPXOR        Y2, Y13, Y13
	VPSHUFB      blake2sRot16<>+0(SB), Y13, Y13
	VPADDD       Y13, Y8, Y8
	VPXOR        Y8, Y7, Y7
	VPSRLD       $0x0c, Y7, Y15
	VPSLLD       $0x14, Y7, Y7
	VPOR         Y15, Y7, Y7
	VPADDD       Y7, Y2, Y2
	VPADDD       256(SP), Y2, Y2
	VPXOR        Y2, Y13, Y13
	VPSHUFB      blake2sRot8<>+0(SB), Y13, Y13
	VPADDD       Y13, Y8, Y8
	VPXOR        Y8, Y7, Y7
	VPSRLD       $0x07, Y7, Y15
	VPSLLD       $0x19, Y7, Y7
	VPOR         Y15, Y7, Y7
	VMOVDQU      512(SP), Y14
	VPADDD       Y4, Y3, Y3
	VPADDD       96(SP), Y3, Y3
	VPXOR        Y3, Y14, Y14
	VPSHUFB      blake2sRot16<>+0(SB), Y14, Y14
	VPADDD       Y14, Y9, Y9
	VPXOR        Y9, Y4, Y4
	VPSRLD       $0x0c, Y4, Y15
	VPSLLD       $0x14, Y4, Y4
	VPOR         Y15, Y4, Y4
	VPADDD       Y4, Y3, Y3
	VPADDD       416(SP), Y3, Y3
	VPXOR        Y3, Y14, Y14
	VPSHUFB      blake2sRot8<>+0(SB), Y14, Y14
	VPADDD       Y14, Y9, Y9
	VPXOR        Y9, Y4, Y4
	VPSRLD       $0x07, Y4, Y15
	VPSLLD       $0x19, Y4, Y4
	VPOR         Y15, Y4, Y4
	VMOVDQU      Y14, 512(SP)
	VPADDD       Y4, Y0, Y0
	VPADDD       64(SP), Y0, Y0
	VPXOR        Y0, Y12, Y12
	VPSHUFB      blake2sRot16<>+0(SB), Y12, Y12
	VPADDD       Y12, Y8, Y8
	VPXOR        Y8, Y4, Y4
	VPSRLD       $0x0c, Y4, Y15
	VPSLLD       $0x14, Y4, Y4
	VPOR         Y15, Y4, Y4
	VPADDD       Y4, Y0, Y0
	VPADDD       384(SP), Y0, Y0
	VPXOR        Y0, Y12, Y12
	VPSHUFB      blake2sRot8<>+0(SB), Y12, Y12
	VPADDD       Y12, Y8, Y8
	VPXOR        Y8, Y4, Y4
	VPSRLD       $0x07, Y4, Y15
	VPSLLD       $0x19, Y4, Y4
	VPOR         Y15, Y4, Y4
	VPADDD       Y5, Y1, Y1
	VPADDD       192(SP), Y1, Y1
	VPXOR        Y1, Y13, Y13
	VPSHUFB      blake2sRot16<>+0(SB), Y13, Y13
	VPADDD       Y13, Y9, Y9
	VPXOR        Y9, Y5, Y5
	VPSRLD       $0x0c, Y5, Y15
	VPSLLD       $0x14, Y5, Y5
	VPOR         Y15, Y5, Y5
	VPADDD       Y5, Y1, Y1
	VPADDD       320(SP), Y1, Y1
	VPXOR        Y1, Y13, Y13
	VPSHUFB      blake2sRot8<>+0(SB), Y13, Y13
	VPADDD       Y13, Y9, Y9
	VPXOR        Y9, Y5, Y5
	VPSRLD       $0x07, Y5, Y15
	VPSLLD       $0x19, Y5, Y5
	VPOR         Y15, Y5, Y5
	VMOVDQU      512(SP), Y14
	VPADDD       Y6, Y2, Y2
	VPADDD       (SP), Y2, Y2
	VPXOR        Y2, Y14, Y14
	VPSHUFB      blake2sRot16<>+0(SB), Y14, Y14
	VPADDD       Y14, Y10, Y10
	VPXOR        Y10, Y6, Y6
	VPSRLD       $0x0c, Y6, Y15
	VPSLLD       $0x14, Y6, Y6
	VPOR         Y15, Y6, Y6
	VPADDD       Y6, Y2, Y2
	VPADDD       352(SP), Y2, Y2
	VPXOR        Y2, Y14, Y14
	VPSHUFB      blake2sRot8<>+0(SB), Y14, Y14
	VPADDD       Y14, Y10, Y10
	VPXOR        Y10, Y6, Y6
	VPSRLD       $0x07, Y6, Y15
	VPSLLD       $0x19, Y6, Y6
	VPOR         Y15, Y6, Y6
	VMOVDQU      Y14, 512(SP)
	VMOVDQU      544(SP), Y14
	VPADDD       Y7, Y3, Y3
	VPADDD       256(SP), Y3, Y3
	VPXOR        Y3, Y14, Y14
	VPSHUFB      blake2sRot16<>+0(SB), Y14, Y14
	VPADDD       Y14, Y11, Y11
	VPXOR        Y11, Y7, Y7
	VPSRLD       $0x0c, Y7, Y15
	VPSLLD       $0x14, Y7, Y7
	VPOR         Y15, Y7, Y7
	VPADDD       Y7, Y3, Y3
	VPADDD       96(SP), Y3, Y3
	VPXOR        Y3, Y14, Y14
	VPSHUFB      blake2sRot8<>+0(SB), Y14, Y14
	VPADDD       Y14, Y11, Y11
	VPXOR        Y11, Y7, Y7
	VPSRLD       $0x07, Y7, Y15
	VPSLLD       $0x19, Y7, Y7
	VPOR         Y15, Y7, Y7
	VMOVDQU      Y14, 544(SP)
	VMOVDQU      544(SP), Y14
	VPADDD       Y5, Y0, Y0
	VPADDD       128(SP), Y0, Y0
	VPXOR        Y0, Y14, Y14
	VPSHUFB      blake2sRot16<>+0(SB), Y14, Y14
	VPADDD       Y14, Y10, Y10
	VPXOR        Y10, Y5, Y5
	VPSRLD       $0x0c, Y5, Y15
	VPSLLD       $0x14, Y5, Y5
	VPOR         Y15, Y5, Y5
	VPADDD       Y5, Y0, Y0
	VPADDD       416(SP), Y0, Y0
	VPXOR        Y0, Y14, Y14
	VPSHUFB      blake2sRot8<>+0(SB), Y14, Y14
	VPADDD       Y14, Y10, Y10
	VPXOR        Y10, Y5, Y5
	VPSRLD       $0x07, Y5, Y15
	VPSLLD       $0x19, Y5, Y5
	VPOR         Y15, Y5, Y5
	VMOVDQU      Y14, 544(SP)
	VPADDD       Y6, Y1, Y1
	VPADDD       224(SP), Y1, Y1
	VPXOR        Y1, Y12, Y12
	VPSHUFB      blake2sRot16<>+0(SB), Y12, Y12
	VPADDD       Y12, Y11, Y11
	VPXOR        Y11, Y6, Y6
	VPSRLD       $0x0c, Y6, Y15
	VPSLLD       $0x14, Y6, Y6
	VPOR         Y15, Y6, Y6
	VPADDD       Y6, Y1, Y1
	VPADDD       160(SP), Y1, Y1
	VPXOR        Y1, Y12, Y12
	VPSHUFB      blake2sRot8<>+0(SB), Y12, Y12
	VPADDD       Y12, Y11, Y11
	VPXOR        Y11, Y6, Y6
	VPSRLD       $0x07, Y6, Y15
	VPSLLD       $0x19, Y6, Y6
	VPOR         Y15, Y6, Y6
	VPADDD       Y7, Y2, Y2
	VPADDD       480(SP), Y2, Y2
	VPXOR        Y2, Y13, Y13
	VPSHUFB      blake2sRot16<>+0(SB), Y13, Y13
	VPADDD       Y13, Y8, Y8
	VPXOR        Y8, Y7, Y7
	VPSRLD       $0x0c, Y7, Y15
	VPSLLD       $0x14, Y7, Y7
	VPOR         Y15, Y7, Y7
	VPADDD       Y7, Y2, Y2
	VPADDD       448(SP), Y2, Y2
	VPXOR        Y2, Y13, Y13
	VPSHUFB      blake2sRot8<>+0(SB), Y13, Y13
	VPADDD       Y13, Y8, Y8
	VPXOR        Y8, Y7, Y7
	VPSRLD       $0x07, Y7, Y15
	VPSLLD       $0x19, Y7, Y7
	VPOR         Y15, Y7, Y7
	VMOVDQU      512(SP), Y14
	VPADDD       Y4, Y3, Y3
	VPADDD       32(SP), Y3, Y3
	VPXOR        Y3, Y14, Y14
	VPSHUFB      blake2sRot16<>+0(SB), Y14, Y14
	VPADDD       Y14, Y9, Y9
	VPXOR        Y9, Y4, Y4
	VPSRLD       $0x0c, Y4, Y15
	VPSLLD       $0x14, Y4, Y4
	VPOR         Y15, Y4, Y4
	VPADDD       Y4, Y3, Y3
	VPADDD       288(SP), Y3, Y3
	VPXOR        Y3, Y14, Y14
	VPSHUFB      blake2sRot8<>+0(SB), Y14, Y14
	VPADDD       Y14, Y9, Y9
	VPXOR        Y9, Y4, Y4
	VPSRLD       $0x07, Y4, Y15
	VPSLLD       $0x19, Y4, Y4
	VPOR         Y15, Y4, Y4
	VMOVDQU      Y14, 512(SP)
	VPADDD       Y4, Y0, Y0
	VPADDD       384(SP), Y0, Y0
	VPXOR        Y0, Y12, Y12
	VPSHUFB      blake2sRot16<>+0(SB), Y12, Y12
	VPADDD       Y12, Y8, Y8
	VPXOR        Y8, Y4, Y4
	VPSRLD       $0x0c, Y4, Y15
	VPSLLD       $0x14, Y4, Y4
	VPOR         Y15, Y4, Y4
	VPADDD       Y4, Y0, Y0
	VPADDD       160(SP), Y0, Y0
	VPXOR        Y0, Y12, Y12
	VPSHUFB      blake2sRot8<>+0(SB), Y12, Y12
	VPADDD       Y12, Y8, Y8
	VPXOR        Y8, Y4, Y4
	VPSRLD       $0x07, Y4, Y15
	VPSLLD       $0x19, Y4, Y4
	VPOR         Y15, Y4, Y4
	VPADDD       Y5, Y1, Y1
	VPADDD       32(SP), Y1, Y1
	VPXOR        Y1, Y13, Y13
	VPSHUFB      blake2sRot16<>+0(SB), Y13, Y13
	VPADDD       Y13, Y9, Y9
	VPXOR        Y9, Y5, Y5
	VPSRLD       $0x0c, Y5, Y15
	VPSLLD       $0x14, Y5, Y5
	VPOR         Y15, Y5, Y5
	VPADDD       Y5, Y1, Y1
	VPADDD       480(SP), Y1, Y1
	VPXOR        Y1, Y13, Y13
	VPSHUFB      blake2sRot8<>+0(SB), Y13, Y13
	VPADDD       Y13, Y9, Y9
	VPXOR        Y9, Y5, Y5
	VPSRLD       $0x07, Y5, Y15
	VPSLLD       $0x19, Y5, Y5
	VPOR         Y15, Y5, Y5
	VMOVDQU      512(SP), Y14
	VPADDD       Y6, Y2, Y2
	VPADDD       448(SP), Y2, Y2
	VPXOR        Y2, Y14, Y14
	VPSHUFB      blake2sRot16<>+0(SB), Y14, Y14
	VPADDD       Y14, Y10, Y10
	VPXOR        Y10, Y6, Y6
	VPSRLD       $0x0c, Y6, Y15
	VPSLLD       $0x14, Y6, Y6
	VPOR         Y15, Y6, Y6
	VPADDD       Y6, Y2, Y2
	VPADDD       416(SP), Y2, Y2
	VPXOR        Y2, Y14, Y14
	VPSHUFB      blake2sRot8<>+0(SB), Y14, Y14
	VPADDD       Y14, Y10, Y10
	VPXOR        Y10, Y6, Y6
	VPSRLD       $0x07, Y6, Y15
	VPSLLD       $0x19, Y6, Y6
	VPOR         Y15, Y6, Y6
	VMOVDQU      Y14, 512(SP)
	VMOVDQU      544(SP), Y14
	VPADDD       Y7, Y3, Y3
	VPADDD       128(SP), Y3, Y3
	VPXOR        Y3, Y14, Y14
	VPSHUFB      blake2sRot16<>+0(SB), Y14, Y14
	VPADDD       Y14, Y11, Y11
	VPXOR        Y11, Y7, Y7
	VPSRLD       $0x0c, Y7, Y15
	VPSLLD       $0x14, Y7, Y7
	VPOR         Y15, Y7, Y7
	VPADDD       Y7, Y3, Y3
	VPADDD       320(SP), Y3, Y3
	VPXOR        Y3, Y14, Y14
	VPSHUFB      blake2sRot8<>+0(SB), Y14, Y14
	VPADDD       Y14, Y11, Y11
	VPXOR        Y11, Y7, Y7
	VPSRLD       $0x07, Y7, Y15
	VPSLLD       $0x19, Y7, Y7
	VPOR         Y15, Y7, Y7
	VMOVDQU      Y14, 544(SP)
	VMOVDQU      544(SP), Y14
	VPADDD       Y5, Y0, Y0
	VPADDD       (SP), Y0, Y0
	VPXOR        Y0, Y14, Y14
	VPSHUFB      blake2sRot16<>+0(SB), Y14, Y14
	VPADDD       Y14, Y10, Y10
	VPXOR        Y10, Y5, Y5
	VPSRLD       $0x0c, Y5, Y15
	VPSLLD       $0x14, Y5, Y5
	VPOR         Y15, Y5, Y5
	VPADDD       Y5, Y0, Y0
	VPADDD       224(SP), Y0, Y0
	VPXOR        Y0, Y14, Y14
	VPSHUFB      blake2sRot8<>+0(SB), Y14, Y14
	VPADDD       Y14, Y10, Y10
	VPXOR        Y10, Y5, Y5
	VPSRLD       $0x07, Y5, Y15
	VPSLLD       $0x19, Y5, Y5
	VPOR         Y15, Y5, Y5
	VMOVDQU      Y14, 544(SP)
	VPADDD       Y6, Y1, Y1
	VPADDD       192(SP), Y1, Y1
	VPXOR        Y1, Y12, Y12
	VPSHUFB      blake2sRot16<>+0(SB), Y12, Y12
	VPADDD       Y12, Y11, Y11
	VPXOR        Y11, Y6, Y6
	VPSRLD       $0x0c, Y6, Y15
	VPSLLD       $0x14, Y6, Y6
	VPOR         Y15, Y6, Y6
	VPADDD       Y6, Y1, Y1
	VPADDD       96(SP), Y1, Y1
	VPXOR        Y1, Y12, Y12
	VPSHUFB      blake2sRot8<>+0(SB), Y12, Y12
	VPADDD       Y12, Y11, Y11
	VPXOR        Y11, Y6, Y6
	VPSRLD       $0x07, Y6, Y15
	VPSLLD       $0x19, Y6, Y6
	VPOR         Y15, Y6, Y6
	VPADDD       Y7, Y2, Y2
	VPADDD       288(SP), Y2, Y2
	VPXOR        Y2, Y13, Y13
	VPSHUFB      blake2sRot16<>+0(SB), Y13, Y13
	VPADDD       Y13, Y8, Y8
	VPXOR        Y8, Y7, Y7
	VPSRLD       $0x0c, Y7, Y15
	VPSLLD       $0x14, Y7, Y7
	VPOR         Y15, Y7, Y7
	VPADDD       Y7, Y2, Y2
	VPADDD       64(SP), Y2, Y2
	VPXOR        Y2, Y13, Y13
	VPSHUFB      blake2sRot8<>+0(SB), Y13, Y13
	VPADDD       Y13, Y8, Y8
	VPXOR        Y8, Y7, Y7
	VPSRLD       $0x07, Y7, Y15
	VPSLLD       $0x19, Y7, Y7
	VPOR         Y15, Y7, Y7
	VMOVDQU      512(SP), Y14
	VPADDD       Y4, Y3, Y3
	VPADDD       256(SP), Y3, Y3
	VPXOR        Y3, Y14, Y14
	VPSHUFB      blake2sRot16<>+0(SB), Y14, Y14
	VPADDD       Y14, Y9, Y9
	VPXOR        Y9, Y4, Y4
	VPSRLD       $0x0c, Y4, Y15
	VPSLLD       $0x14, Y4, Y4
	VPOR         Y15, Y4, Y4
	VPADDD       Y4, Y3, Y3
	VPADDD       352(SP), Y3, Y3
	VPXOR        Y3, Y14, Y14
	VPSHUFB      blake2sRot8<>+0(SB), Y14, Y14
	VPADDD       Y14, Y9, Y9
	VPXOR        Y9, Y4, Y4
	VPSRLD       $0x07, Y4, Y15
	VPSLLD       $0x19, Y4, Y4
	VPOR         Y15, Y4, Y4
	VMOVDQU      Y14, 512(SP)
	VPADDD       Y4, Y0, Y0
	VPADDD       416(SP), Y0, Y0
	VPXOR        Y0, Y12, Y12
	VPSHUFB      blake2sRot16<>+0(SB), Y12, Y12
	VPADDD       Y12, Y8, Y8
	VPXOR        Y8, Y4, Y4
	VPSRLD       $0x0c, Y4, Y15
	VPSLLD       $0x14, Y4, Y4
	VPOR         Y15, Y4, Y4
	VPADDD       Y4, Y0, Y0
	VPADDD       352(SP), Y0, Y0
	VPXOR        Y0, Y12, Y12
	VPSHUFB      blake2sRot8<>+0(SB), Y12, Y12
	VPADDD       Y12, Y8, Y8
	VPXOR        Y8, Y4, Y4
	VPSRLD       $0x07, Y4, Y15
	VPSLLD       $0x19, Y4, Y4
	VPOR         Y15, Y4, Y4
	VPADDD       Y5, Y1, Y1
	VPADDD       224(SP), Y1, Y1
	VPXOR        Y1, Y13, Y13
	VPSHUFB      blake2sRot16<>+0(SB), Y13, Y13
	VPADDD       Y13, Y9, Y9
	VPXOR        Y9, Y5, Y5
	VPSRLD       $0x0c, Y5, Y15
	VPSLLD       $0x14, Y5, Y5
	VPOR         Y15, Y5, Y5
	VPADDD       Y5, Y1, Y1
	VPADDD       448(SP), Y1, Y1
	VPXOR        Y1, Y13, Y13
	VPSHUFB      blake2sRot8<>+0(SB), Y13, Y13
	VPADDD       Y13, Y9, Y9
	VPXOR        Y9, Y5, Y5
	VPSRLD       $0x07, Y5, Y15
	VPSLLD       $0x19, Y5, Y5
	VPOR         Y15, Y5, Y5
	VMOVDQU      512(SP), Y14
	VPADDD       Y6, Y2, Y2
	VPADDD       384(SP), Y2, Y2
	VPXOR        Y2, Y14, Y14
	VPSHUFB      blake2sRot16<>+0(SB), Y14, Y14
	VPADDD       Y14, Y10, Y10
	VPXOR        Y10, Y6, Y6
	VPSRLD       $0x0c, Y6, Y15
	VPSLLD       $0x14, Y6, Y6
	VPOR         Y15, Y6, Y6
	VPADDD       Y6, Y2, Y2
	VPADDD       32(SP), Y2, Y2
	VPXOR        Y2, Y14, Y14
	VPSHUFB      blake2sRot8<>+0(SB), Y14, Y14
	VPADDD       Y14, Y10, Y10
	VPXOR        Y10, Y6, Y6
	VPSRLD       $0x07, Y6, Y15
	VPSLLD       $0x19, Y6, Y6
	VPOR         Y15, Y6, Y6
	VMOVDQU      Y14, 512(SP)
	VMOVDQU      544(SP), Y14
	VPADDD       Y7, Y3, Y3
	VPADDD       96(SP), Y3, Y3
	VPXOR        Y3, Y14, Y14
	VPSHUFB      blake2sRot16<>+0(SB), Y14, Y14
	VPADDD       Y14, Y11, Y11
	VPXOR        Y11, Y7, Y7
	VPSRLD       $0x0c, Y7, Y15
	VPSLLD       $0x14, Y7, Y7
	VPOR         Y15, Y7, Y7
	VPADDD       Y7, Y3, Y3
	VPADDD       288(SP), Y3, Y3
	VPXOR        Y3, Y14, Y14
	VPSHUFB      blake2sRot8<>+0(SB), Y14, Y14
	VPADDD       Y14, Y11, Y11
	VPXOR        Y11, Y7, Y7
	VPSRLD       $0x07, Y7, Y15
	VPSLLD       $0x19, Y7, Y7
	VPOR         Y15, Y7, Y7
	VMOVDQU      Y14, 544(SP)
	VMOVDQU      544(SP), Y14
	VPADDD       Y5, Y0, Y0
	VPADDD       160(SP), Y0, Y0
	VPXOR        Y0, Y14, Y14
	VPSHUFB      blake2sRot16<>+0(SB), Y14, Y14
	VPADDD       Y14, Y10, Y10
	VPXOR        Y10, Y5, Y5
	VPSRLD       $0x0c, Y5, Y15
	VPSLLD       $0x14, Y5, Y5
	VPOR         Y15, Y5, Y5
	VPADDD       Y5, Y0, Y0
	VPADDD       (SP), Y0, Y0
	VPXOR        Y0, Y14, Y14
	VPSHUFB      blake2sRot8<>+0(SB), Y14, Y14
	VPADDD       Y14, Y10, Y10
	VPXOR        Y10, Y5, Y5
	VPSRLD       $0x07, Y5, Y15
	VPSLLD       $0x19, Y5, Y5
	VPOR         Y15, Y5, Y5
	VMOVDQU      Y14, 544(SP)
	VPADDD       Y6, Y1, Y1
	VPADDD       480(SP), Y1, Y1
	VPXOR        Y1, Y12, Y12
	VPSHUFB      blake2sRot16<>+0(SB), Y12, Y12
	VPADDD       Y12, Y11, Y11
	VPXOR        Y11, Y6, Y6
	VPSRLD       $0x0c, Y6, Y15
	VPSLLD       $0x14, Y6, Y6
	VPOR         Y15, Y6, Y6
	VPADDD       Y6, Y1, Y1
	VPADDD       128(SP), Y1, Y1
	VPXOR        Y1, Y12, Y12
	VPSHUFB      blake2sRot8<>+0(SB), Y12, Y12
	VPADDD       Y12, Y11, Y11
	VPXOR        Y11, Y6, Y6
	VPSRLD       $0x07, Y6, Y15
	VPSLLD       $0x19, Y6, Y6
	VPOR         Y15, Y6, Y6
	VPADDD       Y7, Y2, Y2
	VPADDD       256(SP), Y2, Y2
	VPXOR        Y2, Y13, Y13
	VPSHUFB      blake2sRot16<>+0(SB), Y13, Y13
	VPADDD       Y13, Y8, Y8
	VPXOR        Y8, Y7, Y7
	VPSRLD       $0x0c, Y7, Y15
	VPSLLD       $0x14, Y7, Y7
	VPOR         Y15, Y7, Y7
	VPADDD       Y7, Y2, Y2
	VPADDD       192(SP), Y2, Y2
	VPXOR        Y2, Y13, Y13
	VPSHUFB      blake2sRot8<>+0(SB), Y13, Y13
	VPADDD       Y13, Y8, Y8
	VPXOR        Y8, Y7, Y7
	VPSRLD       $0x07, Y7, Y15
	VPSLLD       $0x19, Y7, Y7
	VPOR         Y15, Y7, Y7
	VMOVDQU      512(SP), Y14
	VPADDD       Y4, Y3, Y3
	VPADDD       64(SP), Y3, Y3
	VPXOR        Y3, Y14, Y14
	VPSHUFB      blake2sRot16<>+0(SB), Y14, Y14
	VPADDD       Y14, Y9, Y9
	VPXOR        Y9, Y4, Y4
	VPSRLD       $0x0c, Y4, Y15
	VPSLLD       $0x14, Y4, Y4
	VPOR         Y15, Y4, Y4
	VPADDD       Y4, Y3, Y3
	VPADDD       320(SP), Y3, Y3
	VPXOR        Y3, Y14, Y14
	VPSHUFB      blake2sRot8<>+0(SB), Y14, Y14
	VPADDD       Y14, Y9, Y9
	VPXOR        Y9, Y4, Y4
	VPSRLD       $0x07, Y4, Y15
	VPSLLD       $0x19, Y4, Y4
	VPOR         Y15, Y4, Y4
	VMOVDQU      Y14, 512(SP)
	VPADDD       Y4, Y0, Y0
	VPADDD       192(SP), Y0, Y0
	VPXOR        Y0, Y12, Y12
	VPSHUFB      blake2sRot16<>+0(SB), Y12, Y12
	VPADDD       Y12, Y8, Y8
	VPXOR        Y8, Y4, Y4
	VPSRLD       $0x0c, Y4, Y15
	VPSLLD       $0x14, Y4, Y4
	VPOR         Y15, Y4, Y4
	VPADDD       Y4, Y0, Y0
	VPADDD       480(SP), Y0, Y0
	VPXOR        Y0, Y12, Y12
	VPSHUFB      blake2sRot8<>+0(SB), Y12, Y12
	VPADDD       Y12, Y8, Y8
	VPXOR        Y8, Y4, Y4
	VPSRLD       $0x07, Y4, Y15
	VPSLLD       $0x19, Y4, Y4
	VPOR         Y15, Y4, Y4
	VPADDD       Y5, Y1, Y1
	VPADDD       448(SP), Y1, Y1
	VPXOR        Y1, Y13, Y13
	VPSHUFB      blake2sRot16<>+0(SB), Y13, Y13
	VPADDD       Y13, Y9, Y9
	VPXOR        Y9, Y5, Y5
	VPSRLD       $0x0c, Y5, Y15
	VPSLLD       $0x14, Y5, Y5
	VPOR         Y15, Y5, Y5
	VPADDD       Y5, Y1, Y1
	VPADDD       288(SP), Y1, Y1
	VPXOR        Y1, Y13, Y13
	VPSHUFB      blake2sRot8<>+0(SB), Y13, Y13
	VPADDD       Y13, Y9, Y9
	VPXOR        Y9, Y5, Y5
	VPSRLD       $0x07, Y5, Y15
	VPSLLD       $0x19, Y5, Y5
	VPOR         Y15, Y5, Y5
	VMOVDQU      512(SP), Y14
	VPADDD       Y6, Y2, Y2
	VPADDD       352(SP), Y2, Y2
	VPXOR        Y2, Y14, Y14
	VPSHUFB      blake2sRot16<>+0(SB), Y14, Y14
	VPADDD       Y14, Y10, Y10
	VPXOR        Y10, Y6, Y6
	VPSRLD       $0x0c, Y6, Y15
	VPSLLD       $0x14, Y6, Y6
	VPOR         Y15, Y6, Y6
	VPADDD       Y6, Y2, Y2
	VPADDD       96(SP), Y2, Y2
	VPXOR        Y2, Y14, Y14
	VPSHUFB      blake2sRot8<>+0(SB), Y14, Y14
	VPADDD       Y14, Y10, Y10
	VPXOR        Y10, Y6, Y6
	VPSRLD       $0x07, Y6, Y15
	VPSLLD       $0x19, Y6, Y6
	VPOR         Y15, Y6, Y6
	VMOVDQU      Y14, 512(SP)
	VMOVDQU      544(SP), Y14
	VPADDD       Y7, Y3, Y3
	VPADDD       (SP), Y3, Y3
	VPXOR        Y3, Y14, Y14
	VPSHUFB      blake2sRot16<>+0(SB), Y14, Y14
	VPADDD       Y14, Y11, Y11
	VPXOR        Y11, Y7, Y7
	VPSRLD       $0x0c, Y7, Y15
	VPSLLD       $0x14, Y7, Y7
	VPOR         Y15, Y7, Y7
	VPADDD       Y7, Y3, Y3
	VPADDD       256(SP), Y3, Y3
	VPXOR        Y3, Y14, Y14
	VPSHUFB      blake2sRot8<>+0(SB), Y14, Y14
	VPADDD       Y14, Y11, Y11
	VPXOR        Y11, Y7, Y7
	VPSRLD       $0x07, Y7, Y15
	VPSLLD       $0x19, Y7, Y7
	VPOR         Y15, Y7, Y7
	VMOVDQU      Y14, 544(SP)
	VMOVDQU      544(SP), Y14
	VPADDD       Y5, Y0, Y0
	VPADDD       384(SP), Y0, Y0
	VPXOR        Y0, Y14, Y14
	VPSHUFB      blake2sRot16<>+0(SB), Y14, Y14
	VPADDD       Y14, Y10, Y10
	VPXOR        Y10, Y5, Y5
	VPSRLD       $0x0c, Y5, Y15
	VPSLLD       $0x14, Y5, Y5
	VPOR         Y15, Y5, Y5
	VPADDD       Y5, Y0, Y0
	VPADDD       64(SP), Y0, Y0
	VPXOR        Y0, Y14, Y14
	VPSHUFB      blake2sRot8<>+0(SB), Y14, Y14
	VPADDD       Y14, Y10, Y10
	VPXOR        Y10, Y5, Y5
	VPSRLD       $0x07, Y5, Y15
	VPSLLD       $0x19, Y5, Y5
	VPOR         Y15, Y5, Y5
	VMOVDQU      Y14, 544(SP)
	VPADDD       Y6, Y1, Y1
	VPADDD       416(SP), Y1, Y1
	VPXOR        Y1, Y12, Y12
	VPSHUFB      blake2sRot16<>+0(SB), Y12, Y12
	VPADDD       Y12, Y11, Y11
	VPXOR        Y11, Y6, Y6
	VPSRLD       $0x0c, Y6, Y15
	VPSLLD       $0x14, Y6, Y6
	VPOR         Y15, Y6, Y6
	VPADDD       Y6, Y1, Y1
	VPADDD       224(SP), Y1, Y1
	VPXOR        Y1, Y12, Y12
	VPSHUFB      blake2sRot8<>+0(SB), Y12, Y12
	VPADDD       Y12, Y11, Y11
	VPXOR        Y11, Y6, Y6
	VPSRLD       $0x07, Y6, Y15
	VPSLLD       $0x19, Y6, Y6
	VPOR         Y15, Y6, Y6
	VPADDD       Y7, Y2, Y2
	VPADDD       32(SP), Y2, Y2
	VPXOR        Y2, Y13, Y13
	VPSHUFB      blake2sRot16<>+0(SB), Y13, Y13
	VPADDD       Y13, Y8, Y8
	VPXOR        Y8, Y7, Y7
	VPSRLD       $0x0c, Y7, Y15
	VPSLLD       $0x14, Y7, Y7
	VPOR         Y15, Y7, Y7
	VPADDD       Y7, Y2, Y2
	VPADDD       128(SP), Y2, Y2
	VPXOR        Y2, Y13, Y13
	VPSHUFB      blake2sRot8<>+0(SB), Y13, Y13
	VPADDD       Y13, Y8, Y8
	VPXOR        Y8, Y7, Y7
	VPSRLD       $0x07, Y7, Y15
	VPSLLD       $0x19, Y7, Y7
	VPOR         Y15, Y7, Y7
	VMOVDQU      512(SP), Y14
	VPADDD       Y4, Y3, Y3
	VPADDD       320(SP), Y3, Y3
	VPXOR        Y3, Y14, Y14
	VPSHUFB      blake2sRot16<>+0(SB), Y14, Y14
	VPADDD       Y14, Y9, Y9
	VPXOR        Y9, Y4, Y4
	VPSRLD       $0x0c, Y4, Y15
	VPSLLD       $0x14, Y4, Y4
	VPOR         Y15, Y4, Y4
	VPADDD       Y4, Y3, Y3
	VPADDD       160(SP), Y3, Y3
	VPXOR        Y3, Y14, Y14
	VPSHUFB      blake2sRot8<>+0(SB), Y14, Y14
	VPADDD       Y14, Y9, Y9
	VPXOR        Y9, Y4, Y4
	VPSRLD       $0x07, Y4, Y15
	VPSLLD       $0x19, Y4, Y4
	VPOR         Y15, Y4, Y4
	VMOVDQU      Y14, 512(SP)
	VPADDD       Y4, Y0, Y0
	VPADDD       320(SP), Y0, Y0
	VPXOR        Y0, Y12, Y12
	VPSHUFB      blake2sRot16<>+0(SB), Y12, Y12
	VPADDD       Y12, Y8, Y8
	VPXOR        Y8, Y4, Y4
	VPSRLD       $0x0c, Y4, Y15
	VPSLLD       $0x14, Y4, Y4
	VPOR         Y15, Y4, Y4
	VPADDD       Y4, Y0, Y0
	VPADDD       64(SP), Y0, Y0
	VPXOR        Y0, Y12, Y12
	VPSHUFB      blake2sRot8<>+0(SB), Y12, Y12
	VPADDD       Y12, Y8, Y8
	VPXOR        Y8, Y4, Y4
	VPSRLD       $0x07, Y4, Y15
	VPSLLD       $0x19, Y4, Y4
	VPOR         Y15, Y4, Y4
	VPADDD       Y5, Y1, Y1
	VPADDD       256(SP), Y1, Y1
	VPXOR        Y1, Y13, Y13
	VPSHUFB      blake2sRot16<>+0(SB), Y13, Y13
	VPADDD       Y13, Y9, Y9
	VPXOR        Y9, Y5, Y5
	VPSRLD       $0x0c, Y5, Y15
	VPSLLD       $0x14, Y5, Y5
	VPOR         Y15, Y5, Y5
	VPADDD       Y5, Y1, Y1
	VPADDD       128(SP), Y1, Y1
	VPXOR        Y1, Y13, Y13
	VPSHUFB      blake2sRot8<>+0(SB), Y13, Y13
	VPADDD       Y13, Y9, Y9
	VPXOR        Y9, Y5, Y5
	VPSRLD       $0x07, Y5, Y15
	VPSLLD       $0x19, Y5, Y5
	VPOR         Y15, Y5, Y5
	VMOVDQU      512(SP), Y14
	VPADDD       Y6, Y2, Y2
	VPADDD       224(SP), Y2, Y2
	VPXOR        Y2, Y14, Y14
	VPSHUFB      blake2sRot16<>+0(SB), Y14, Y14
	VPADDD       Y14, Y10, Y10
	VPXOR        Y10, Y6, Y6
	VPSRLD       $0x0c, Y6, Y15
	VPSLLD       $0x14, Y6, Y6
	VPOR         Y15, Y6, Y6
	VPADDD       Y6, Y2, Y2
	VPADDD       192(SP), Y2, Y2
	VPXOR        Y2, Y14, Y14
	VPSHUFB      blake2sRot8<>+0(SB), Y14, Y14
	VPADDD       Y14, Y10, Y10
	VPXOR        Y10, Y6, Y6
	VPSRLD       $0x07, Y6, Y15
	VPSLLD       $0x19, Y6, Y6
	VPOR         Y15, Y6, Y6
	VMOVDQU      Y14, 512(SP)
	VMOVDQU      544(SP), Y14
	VPADDD       Y7, Y3, Y3
	VPADDD       32(SP), Y3, Y3
	VPXOR        Y3, Y14, Y14
	VPSHUFB      blake2sRot16<>+0(SB), Y14, Y14
	VPADDD       Y14, Y11, Y11
	VPXOR        Y11, Y7, Y7
	VPSRLD       $0x0c, Y7, Y15
	VPSLLD       $0x14, Y7, Y7
	VPOR         Y15, Y7, Y7
	VPADDD       Y7, Y3, Y3
	VPADDD       160(SP), Y3, Y3
	VPXOR        Y3, Y14, Y14
	VPSHUFB      blake2sRot8<>+0(SB), Y14, Y14
	VPADDD       Y14, Y11, Y11
	VPXOR        Y11, Y7, Y7
	VPSRLD       $0x07, Y7, Y15
	VPSLLD       $0x19, Y7, Y7
	VPOR         Y15, Y7, Y7
	VMOVDQU      Y14, 544(SP)
	VMOVDQU      544(SP), Y14
	VPADDD       Y5, Y0, Y0
	VPADDD       480(SP), Y0, Y0
	VPXOR        Y0, Y14, Y14
	VPSHUFB      blake2sRot16<>+0(SB), Y14, Y14
	VPADDD       Y14, Y10, Y10
	VPXOR        Y10, Y5, Y5
	VPSRLD       $0x0c, Y5, Y15
	VPSLLD       $0x14, Y5, Y5
	VPOR         Y15, Y5, Y5
	VPADDD       Y5, Y0, Y0
	VPADDD       352(SP), Y0, Y0
	VPXOR        Y0, Y14, Y14
	VPSHUFB      blake2sRot8<>+0(SB), Y14, Y14
	VPADDD       Y14, Y10, Y10
	VPXOR        Y10, Y5, Y5
	VPSRLD       $0x07, Y5, Y15
	VPSLLD       $0x19, Y5, Y5
	VPOR         Y15, Y5, Y5
	VMOVDQU      Y14, 544(SP)
	VPADDD       Y6, Y1, Y1
	VPADDD       288(SP), Y1, Y1
	VPXOR        Y1, Y12, Y12
	VPSHUFB      blake2sRot16<>+0(SB), Y12, Y12
	VPADDD       Y12, Y11, Y11
	VPXOR        Y11, Y6, Y6
	VPSRLD       $0x0c, Y6, Y15
	VPSLLD       $0x14, Y6, Y6
	VPOR         Y15, Y6, Y6
	VPADDD       Y6, Y1, Y1
	VPADDD       448(SP), Y1, Y1
	VPXOR        Y1, Y12, Y12
	VPSHUFB      blake2sRot8<>+0(SB), Y12, Y12
	VPADDD       Y12, Y11, Y11
	VPXOR        Y11, Y6, Y6
	VPSRLD       $0x07, Y6, Y15
	VPSLLD       $0x19, Y6, Y6
	VPOR         Y15, Y6, Y6
	VPADDD       Y7, Y2, Y2
	VPADDD       96(SP), Y2, Y2
	VPXOR        Y2, Y13, Y13
	VPSHUFB      blake2sRot16<>+0(SB), Y13, Y13
	VPADDD       Y13, Y8, Y8
	VPXOR        Y8, Y7, Y7
	VPSRLD       $0x0c, Y7, Y15
	VPSLLD       $0x14, Y7, Y7
	VPOR         Y15, Y7, Y7
	VPADDD       Y7, Y2, Y2
	VPADDD       384(SP), Y2, Y2
	VPXOR        Y2, Y13, Y13
	VPSHUFB      blake2sRot8<>+0(SB), Y13, Y13
	VPADDD       Y13, Y8, Y8
	VPXOR        Y8, Y7, Y7
	VPSRLD       $0x07, Y7, Y15
	VPSLLD       $0x19, Y7, Y7
	VPOR         Y15, Y7, Y7
	VMOVDQU      512(SP), Y14
	VPADDD       Y4, Y3, Y3
	VPADDD       416(SP), Y3, Y3
	VPXOR        Y3, Y14, Y14
	VPSHUFB      blake2sRot16<>+0(SB), Y14, Y14
	VPADDD       Y14, Y9, Y9
	VPXOR        Y9, Y4, Y4
	VPSRLD       $0x0c, Y4, Y15
	VPSLLD       $0x14, Y4, Y4
	VPOR         Y15, Y4, Y4
	VPADDD       Y4, Y3, Y3
	VPADDD       (SP), Y3, Y3
	VPXOR        Y3, Y14, Y14
	VPSHUFB      blake2sRot8<>+0(SB), Y14, Y14
	VPADDD       Y14, Y9, Y9
	VPXOR        Y9, Y4, Y4
	VPSRLD       $0x07, Y4, Y15
	VPSLLD       $0x19, Y4, Y4
	VPOR         Y15, Y4, Y4
	VMOVDQU      Y14, 512(SP)
	VPXOR        Y0, Y8, Y15
	VPXOR        (AX), Y15, Y15
	VMOVDQU      Y15, (AX)
	VPXOR        Y1, Y9, Y15
	VPXOR        32(AX), Y15, Y15
	VMOVDQU      Y15, 32(AX)
	VPXOR        Y2, Y10, Y15
	VPXOR        64(AX), Y15, Y15
	VMOVDQU      Y15, 64(AX)
	VPXOR        Y3, Y11, Y15
	VPXOR        96(AX), Y15, Y15
	VMOVDQU      Y15, 96(AX)
	VPXOR        Y4, Y12, Y15
	VPXOR        128(AX), Y15, Y15
	VMOVDQU      Y15, 128(AX)
	VPXOR        Y5, Y13, Y15
	VPXOR        160(AX), Y15, Y15
	VMOVDQU      Y15, 160(AX)
	VMOVDQU      512(SP), Y15
	VPXOR        Y6, Y15, Y15
	VPXOR        192(AX), Y15, Y15
	VMOVDQU      Y15, 192(AX)
	VMOVDQU      544(SP), Y15
	VPXOR        Y7, Y15, Y15
	VPXOR        224(AX), Y15, Y15
	VMOVDQU      Y15, 224(AX)
	ADDQ         $+512, CX
	DECQ         DX
	JNZ          stride

done:
	VZEROUPPER
	RET
