// Code generated by command: go run blake2sp_gen.go -pkg rarengine -out ../blake2sp_amd64.s -stubs ../blake2sp_amd64.go. DO NOT EDIT.

//go:build amd64

package rarengine

// blake2sp8AVX2 compresses strides consecutive 512-byte strides of p into the
// eight BLAKE2s states in h, lane i of h[j] being word j of leaf i and leaf i
// taking bytes 64*i..64*i+63 of every stride. t is the byte counter the first
// block ends at; it advances by 64 per stride. No block is final.
//
// The design follows nwaples/rardecode's asm/blake2sp_gen.go, Copyright (c)
// 2015, Nicholas Waples, BSD 2-Clause licence; its notice and disclaimer are
// reproduced in THIRD_PARTY_NOTICES at the repository root.
//
//go:noescape
func blake2sp8AVX2(h *[8][8]uint32, p *byte, strides int, t uint64)
