//go:build amd64 && !purego

package rarengine

import (
	"golang.org/x/sys/cpu"
)

// blake2sp_amd64.s and blake2sp_amd64.go are generated by asm/blake2sp_gen.go,
// a separate module so the main one keeps requiring only golang.org/x/sys.
//
// The kernel's design follows nwaples/rardecode; see asm/THIRD_PARTY_NOTICES.
//
//go:generate sh -c "cd asm && GOFLAGS=-mod=mod go run blake2sp_gen.go -pkg rarengine -out ../blake2sp_amd64.s -stubs ../blake2sp_amd64.go"

func init() {
	if cpu.X86.HasAVX2 {
		blake2sp8 = blake2sp8Dispatch
	}
}

// blake2sp8Dispatch adapts the kernel's pointer-and-count signature to the
// slice form blake2sp8 has. The caller guarantees len(p) >= blake2spStride.
func blake2sp8Dispatch(h *[8][8]uint32, p []byte, t uint64) {
	blake2sp8AVX2(h, &p[0], len(p)/blake2spStride, t)
}
