package rarengine

import (
	"errors"
	"io"
	"os"
	"path/filepath"
	"slices"
	"testing"
)

// The tests in this file work on rar-produced archives from testdata, not the
// hand-built blocks the rest of the damage tests assemble.
//
// The builders in reader_test.go and packed_drain_test.go emit a minimal
// store-method block: no extra area, no timestamps, no host-OS fields, and a
// payload the test chose. That is precise about the shape under test and
// proves nothing about the shapes real rar emits, so a member that survives a
// synthetic fixture can still take a different path through the parser in
// the field. These cover the same claims against real archives; both sets
// are wanted.
//
// Ported from unpack_realarchive_test.go (git show 4b9a8a8~1) against the
// deleted UnpackDir/UnpackOptions API, rebuilt here against Reader/Entry.
// NextEntry's errors are archive-level only; a member's verdict comes from
// Entry.Close(). One of the four original tests,
// TestUnpackDir_RealArchive_SkippedMemberIsNotDamage, depended on
// UnpackOptions.OverwriteFiles -- a skip-if-already-on-disk behaviour that
// Reader/Entry has no equivalent of -- so it is not ported.

// fileVolumesOf opens each named file under testdata and returns a channel
// carrying them as volumes, in order. Unlike volumesOf (discard_payload_test.go),
// which wraps in-memory byte slices, this is needed here because the fixtures
// are real files on disk.
func fileVolumesOf(t *testing.T, names ...string) <-chan io.ReadCloser {
	t.Helper()
	ch := make(chan io.ReadCloser, len(names))
	for _, name := range names {
		f, err := os.Open(name)
		if err != nil {
			t.Fatalf("open %s: %v", name, err)
		}
		// The Reader closes each volume it finishes with, but a test that
		// fails early or stops before draining the channel leaves the rest
		// open until the process exits. Close is idempotent on *os.File only
		// in the sense that a second call errors harmlessly, which is what
		// the discard here is for.
		t.Cleanup(func() { _ = f.Close() })
		ch <- f
	}
	close(ch)
	return ch
}

// corruptedCopy writes archive with the byte at off inverted, and returns the
// path of the copy.
func corruptedCopy(t *testing.T, archive string, off int) string {
	t.Helper()

	b, err := os.ReadFile(archive)
	if err != nil {
		t.Fatalf("read fixture: %v", err)
	}
	if off >= len(b) {
		t.Fatalf("offset %d is past the end of a %d-byte fixture; it was regenerated", off, len(b))
	}
	b[off] ^= 0xff

	path := filepath.Join(t.TempDir(), filepath.Base(archive))
	if err := os.WriteFile(path, b, 0600); err != nil {
		t.Fatalf("write corrupted copy: %v", err)
	}
	return path
}

// realArchiveResult is one member's outcome from draining a Reader to
// completion: its name and the verdict Entry.Close() reported (nil on
// success).
type realArchiveResult struct {
	name string
	err  error
}

// drainReader reads every member to completion via io.Copy so each one's
// checksum is verified, then records its Close() verdict. It returns once
// NextEntry reports the archive is over (io.EOF or ErrNoNextVolume); any
// other NextEntry error fails the test immediately, since these tests are
// about per-member damage, not archive-level failure.
func drainReader(t *testing.T, r *Reader) []realArchiveResult {
	t.Helper()
	var results []realArchiveResult
	for {
		e, err := r.NextEntry()
		if err != nil {
			if errors.Is(err, io.EOF) || errors.Is(err, ErrNoNextVolume) {
				return results
			}
			t.Fatalf("NextEntry: %v", err)
		}
		_, _ = io.Copy(io.Discard, e)
		results = append(results, realArchiveResult{name: e.Header.Name, err: e.Close()})
	}
}

func namesOf(results []realArchiveResult) []string {
	out := make([]string, 0, len(results))
	for _, r := range results {
		out = append(out, r.name)
	}
	slices.Sort(out)
	return out
}

// TestReader_RealArchive_PristineIsClean is the negative control for the two
// tests below, and the guard on the fixture itself.
//
// Neither is evidence of anything if the archive is not a healthy two-member
// non-solid archive to begin with -- a fixture regenerated by a different rar
// version could change member count or ordering and leave the corruption
// tests asserting against a shape nobody checked.
func TestReader_RealArchive_PristineIsClean(t *testing.T) {
	r := NewReader(fileVolumesOf(t, filepath.Join("testdata", "rar5_compress.rar")))
	results := drainReader(t, r)

	for _, res := range results {
		if res.err != nil {
			t.Errorf("member %q: %v; want a clean decode", res.name, res.err)
		}
	}
	if got := namesOf(results); !slices.Equal(got, []string{"hello.txt", "second.txt"}) {
		t.Fatalf("fixture is %v; these tests need the two-member non-solid archive", got)
	}
	if r.solid {
		t.Fatalf("fixture archive header declared solid; these tests need non-solid")
	}
}

// TestReader_RealArchive_CorruptedMemberIsSkipped is the feature's central
// claim, tested against an archive rar actually produced: damaging one member
// of a non-solid archive costs you that member and nothing else.
//
// Offset 74 sits in hello.txt's compressed data. It was derived by inverting
// each byte of the fixture in turn and recording the outcome, not chosen by
// reading the layout: bytes 67-81 are hello.txt's payload and 127-135 are
// second.txt's, and everything outside those ranges damages a header instead,
// which is a different failure with a different owner. PristineIsClean above
// catches a regenerated fixture that moves them.
func TestReader_RealArchive_CorruptedMemberIsSkipped(t *testing.T) {
	corrupt := corruptedCopy(t, filepath.Join("testdata", "rar5_compress.rar"), 74)

	r := NewReader(fileVolumesOf(t, corrupt))
	results := drainReader(t, r)

	if got := namesOf(results); !slices.Equal(got, []string{"hello.txt", "second.txt"}) {
		t.Fatalf("got members %v, want both hello.txt and second.txt to be reached "+
			"(damage costs the member its content, not its place in the traversal)", got)
	}

	var damaged, clean int
	for _, res := range results {
		switch res.name {
		case "hello.txt":
			if !errors.Is(res.err, ErrCRCMismatch) {
				t.Errorf("hello.txt verdict = %v, want ErrCRCMismatch", res.err)
			}
			damaged++
		case "second.txt":
			if res.err != nil {
				t.Errorf("second.txt verdict = %v, want a clean decode -- the "+
					"intact member behind the damaged one", res.err)
			}
			clean++
		}
	}
	if damaged != 1 || clean != 1 {
		t.Fatalf("damaged=%d clean=%d; want exactly one of each", damaged, clean)
	}
}

// TestReader_RealArchive_MissingFinalVolume covers the failure this library
// was built for: a Usenet download whose last segment never arrived.
//
// The member cannot be completed, so it is damage -- but ErrNoNextVolume
// means something different at each site. Reaching NextEntry it means the
// archive is over and ends traversal cleanly; reaching a read in progress it
// means THIS member is unfinished. Treating the second as an ordinary
// end-of-archive would report success for a member that never completed.
func TestReader_RealArchive_MissingFinalVolume(t *testing.T) {
	parts, err := filepath.Glob(filepath.Join("testdata", "rar5_multi.part*.rar"))
	if err != nil || len(parts) < 2 {
		t.Fatalf("multi-volume fixture missing: %v (%d parts)", err, len(parts))
	}
	slices.Sort(parts)
	available := parts[:len(parts)-1] // the segment that never arrived is dropped

	r := NewReader(fileVolumesOf(t, available...))

	e, err := r.NextEntry()
	if err != nil {
		t.Fatalf("first NextEntry: %v", err)
	}
	if e.Header.Name != "large.bin" {
		t.Fatalf("member = %q, want large.bin", e.Header.Name)
	}

	_, readErr := io.Copy(io.Discard, e)
	closeErr := e.Close()
	if !errors.Is(readErr, ErrNoNextVolume) && !errors.Is(closeErr, ErrNoNextVolume) {
		t.Fatalf("large.bin: read=%v close=%v; want ErrNoNextVolume from an "+
			"unfinished member", readErr, closeErr)
	}

	// The traversal itself ends cleanly: the next NextEntry call finds the
	// volume channel closed and reports the archive is over, not a per-member
	// failure.
	if _, err := r.NextEntry(); !errors.Is(err, ErrNoNextVolume) && !errors.Is(err, io.EOF) {
		t.Fatalf("NextEntry after the unfinished member = %v, want io.EOF or "+
			"ErrNoNextVolume ending traversal cleanly", err)
	}
}
