package rarengine

import (
	"context"
	"errors"
	"os"
	"path/filepath"
	"slices"
	"testing"
)

// The tests in this file work on rar-produced archives from testdata, not the
// hand-built blocks the rest of the damage tests assemble.
//
// The builders in packed_drain_test.go emit a minimal store-method block: no
// extra area, no timestamps, no host-OS fields, and a payload the test chose.
// That is precise about the shape under test and proves nothing about the
// shapes real rar emits, so a member that survives a synthetic fixture can
// still take a different path through the parser in the field. These cover the
// same claims against real archives; both sets are wanted.

// corruptedCopy writes archive with the byte at off inverted, and returns the
// path of the copy.
func corruptedCopy(t *testing.T, archive string, off int) string {
	t.Helper()

	b, err := os.ReadFile(archive)
	if err != nil {
		t.Fatalf("read fixture: %v", err)
	}
	if off >= len(b) {
		t.Fatalf("offset %d is past the end of a %d-byte fixture; it was regenerated", off, len(b))
	}
	b[off] ^= 0xff

	path := filepath.Join(t.TempDir(), filepath.Base(archive))
	if err := os.WriteFile(path, b, 0600); err != nil {
		t.Fatalf("write corrupted copy: %v", err)
	}
	return path
}

func baseNames(paths []string) []string {
	out := make([]string, 0, len(paths))
	for _, p := range paths {
		out = append(out, filepath.Base(p))
	}
	slices.Sort(out)
	return out
}

// TestUnpackDir_RealArchive_PristineIsClean is the negative control for the
// two tests below, and the guard on the fixture itself.
//
// Neither is evidence of anything if the archive is not a healthy two-member
// non-solid archive to begin with -- a fixture regenerated by a different rar
// version could change member count or ordering and leave the corruption tests
// asserting against a shape nobody checked.
func TestUnpackDir_RealArchive_PristineIsClean(t *testing.T) {
	res, err := UnpackDir(context.Background(),
		filepath.Join("testdata", "rar5_compress.rar"), t.TempDir(), UnpackOptions{})
	if err != nil {
		t.Fatalf("UnpackDir on a healthy archive: %v", err)
	}
	if len(res.Damaged) != 0 {
		t.Errorf("healthy archive reported damage: %+v", res.Damaged)
	}
	if got := baseNames(res.Files); !slices.Equal(got, []string{"hello.txt", "second.txt"}) {
		t.Fatalf("fixture is %v; these tests need the two-member non-solid archive", got)
	}
}

// TestUnpackDir_RealArchive_CorruptedMemberIsSkipped is the feature's central
// claim, tested against an archive rar actually produced: damaging one member
// of a non-solid archive costs you that member and nothing else.
//
// Offset 74 sits in hello.txt's compressed data. It was derived by inverting
// each byte of the fixture in turn and recording the outcome, not chosen by
// reading the layout: bytes 67-81 are hello.txt's payload and 127-135 are
// second.txt's, and everything outside those ranges damages a header instead,
// which is a different failure with a different owner. PristineIsClean above
// catches a regenerated fixture that moves them.
func TestUnpackDir_RealArchive_CorruptedMemberIsSkipped(t *testing.T) {
	out := t.TempDir()
	res, err := UnpackDir(context.Background(),
		corruptedCopy(t, filepath.Join("testdata", "rar5_compress.rar"), 74), out, UnpackOptions{})
	if err != nil {
		t.Fatalf("one corrupt member returned a fatal error: %v", err)
	}

	if got := baseNames(res.Files); !slices.Equal(got, []string{"second.txt"}) {
		t.Errorf("extracted %v; want only second.txt -- the intact member behind the damaged one", got)
	}

	d := onlyDamaged(t, res)
	if d.Header.Name != "hello.txt" {
		t.Errorf("damaged entry names %q; want hello.txt", d.Header.Name)
	}
	if !errors.Is(d.Err, ErrCRCMismatch) {
		t.Errorf("damaged entry carries %v; want ErrCRCMismatch", d.Err)
	}

	if _, err := os.Stat(filepath.Join(out, "hello.txt")); !errors.Is(err, os.ErrNotExist) {
		t.Errorf("the corrupt member was left on disk (stat err %v)", err)
	}
}

// TestUnpackDir_RealArchive_MissingFinalVolume covers the failure this library
// was built for: a Usenet download whose last segment never arrived.
//
// The member cannot be completed, so it is damage -- but ErrNoNextVolume means
// something different at each site. Reaching Next it means the archive is over
// and ends the traversal cleanly; reaching a read in progress it means this
// member is unfinished. Treating the second as an ordinary end-of-archive
// would drop the member from both Files and Damaged and report success.
func TestUnpackDir_RealArchive_MissingFinalVolume(t *testing.T) {
	parts, err := filepath.Glob(filepath.Join("testdata", "rar5_multi.part*.rar"))
	if err != nil || len(parts) < 2 {
		t.Fatalf("multi-volume fixture missing: %v (%d parts)", err, len(parts))
	}
	slices.Sort(parts)
	last := parts[len(parts)-1]

	vols := t.TempDir()
	for _, p := range parts {
		if p == last {
			continue // the segment that never arrived
		}
		b, err := os.ReadFile(p)
		if err != nil {
			t.Fatalf("read %s: %v", p, err)
		}
		if err := os.WriteFile(filepath.Join(vols, filepath.Base(p)), b, 0600); err != nil {
			t.Fatalf("write volume: %v", err)
		}
	}

	out := t.TempDir()
	res, err := UnpackDir(context.Background(), filepath.Join(vols, filepath.Base(parts[0])), out, UnpackOptions{})
	if err != nil {
		t.Fatalf("a missing final volume returned a fatal error: %v", err)
	}

	d := onlyDamaged(t, res)
	if d.Header.Name != "large.bin" {
		t.Errorf("damaged entry names %q; want large.bin", d.Header.Name)
	}
	if !errors.Is(d.Err, ErrNoNextVolume) {
		t.Errorf("damaged entry carries %v; want ErrNoNextVolume", d.Err)
	}
	if len(res.Files) != 0 {
		t.Errorf("reported %v as extracted; the only member could not be completed", res.Files)
	}

	// The bytes that did arrive were written before the failure. A caller that
	// resumes the download must not find a short file here looking complete.
	left, err := os.ReadDir(out)
	if err != nil {
		t.Fatalf("read output dir: %v", err)
	}
	if len(left) != 0 {
		t.Errorf("output directory holds %d entries; the incomplete member must not be left behind", len(left))
	}
}

// TestUnpackDir_RealArchive_SkippedMemberTruncatedIsRecorded covers the member
// this loop never reads.
//
// With the default OverwriteFiles: false, a member already present on disk is
// skipped, so its payload is drained by Next rather than read here. When that
// drain runs out of volumes the failure arrives as a bare ErrNoNextVolume,
// which the Next site treats as end-of-archive -- so the extraction reported
// total success, with no entry in Files OR Damaged, while a stale file sat at
// the destination looking extracted. That is the silent truncation every
// constraint in this library exists to prevent.
func TestUnpackDir_RealArchive_SkippedMemberTruncatedIsRecorded(t *testing.T) {
	parts, err := filepath.Glob(filepath.Join("testdata", "rar5_multi.part*.rar"))
	if err != nil || len(parts) < 2 {
		t.Fatalf("multi-volume fixture missing: %v (%d parts)", err, len(parts))
	}
	slices.Sort(parts)

	vols := t.TempDir()
	for _, p := range parts[:len(parts)-1] { // final segment never arrived
		b, err := os.ReadFile(p)
		if err != nil {
			t.Fatalf("read %s: %v", p, err)
		}
		if err := os.WriteFile(filepath.Join(vols, filepath.Base(p)), b, 0600); err != nil {
			t.Fatalf("write volume: %v", err)
		}
	}

	// A stale copy from an earlier run is what makes the member get skipped.
	out := t.TempDir()
	stale := []byte("stale")
	if err := os.WriteFile(filepath.Join(out, "large.bin"), stale, 0600); err != nil {
		t.Fatalf("seed stale file: %v", err)
	}

	res, err := UnpackDir(context.Background(), filepath.Join(vols, filepath.Base(parts[0])), out,
		UnpackOptions{OverwriteFiles: false})
	if err != nil {
		t.Fatalf("UnpackDir: %v", err)
	}

	d := onlyDamaged(t, res)
	if d.Header.Name != "large.bin" {
		t.Errorf("damaged entry names %q; want large.bin", d.Header.Name)
	}
	if !errors.Is(d.Err, ErrNoNextVolume) {
		t.Errorf("damaged entry carries %v; want ErrNoNextVolume", d.Err)
	}
	if len(res.Files) != 0 {
		t.Errorf("reported %v as extracted; the member was skipped, not written", res.Files)
	}

	// The stale file is left alone -- skipping means not touching it -- but the
	// caller must be told the archive's copy never arrived.
	got, err := os.ReadFile(filepath.Join(out, "large.bin"))
	if err != nil || string(got) != string(stale) {
		t.Errorf("stale file reads %q (%v); skipping must not modify it", got, err)
	}
}
