name: Go CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - name: Checkout Code
      uses: actions/checkout@v7

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version-file: go.mod

    - name: Install unrar (Ubuntu)
      run: |
        sudo apt-get update
        sudo apt-get install -y unrar

    - name: Verify go.mod Tidy
      run: |
        go mod tidy
        git diff --exit-code

    - name: Run Go Vet
      run: go vet ./...

    - name: Run Tests with Race Detector
      run: go test -v -race -shuffle=on ./...

    - name: Run Benchmarks
      run: go test -bench=. -benchmem ./...
